---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-ingressroute-certificate-staging
  namespace: traefik
spec:
  secretName: traefik-certificate-secret-staging
  issuerRef:
    name: cloudflare-clusterissuer-staging
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_CLUSTER_LOCAL_DOMAIN}"
    - "*.${SECRET_CLUSTER_LOCAL_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: observability-ingressroute-certificate-staging
  namespace: observability
spec:
  secretName: observability-certificate-secret-staging
  issuerRef:
    name: cloudflare-clusterissuer-staging
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_CLUSTER_LOCAL_DOMAIN}"
    - "*.${SECRET_CLUSTER_LOCAL_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-ingressroute-certificate-staging
  namespace: default
spec:
  secretName: default-certificate-secret-staging
  issuerRef:
    name: cloudflare-clusterissuer-staging
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_CLUSTER_LOCAL_DOMAIN}"
    - "*.${SECRET_CLUSTER_LOCAL_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-ingressroute-certificate-staging
  namespace: longhorn-system
spec:
  secretName: longhorn-certificate-secret-staging
  issuerRef:
    name: cloudflare-clusterissuer-staging
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_CLUSTER_LOCAL_DOMAIN}"
    - "*.${SECRET_CLUSTER_LOCAL_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: database-ingressroute-certificate-staging
  namespace: database
spec:
  secretName: database-certificate-secret-staging
  issuerRef:
    name: cloudflare-clusterissuer-staging
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_CLUSTER_LOCAL_DOMAIN}"
    - "*.${SECRET_CLUSTER_LOCAL_DOMAIN}"
