---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  CLUSTER: production

dotenv:
  - '{{.KUBERNETES_DIR}}/{{.CLUSTER}}/cluster.env'

includes:
  provision: .taskfiles/provision
  talos: .taskfiles/talos
  bootstrap: .taskfiles/bootstrap
  utils: .taskfiles/utils
  workstation: .taskfiles/workstation

tasks:

  default: task -l

  setup-all:
    desc: Setup all the things
    cmds:
      - {task: provision:download-talos-to-proxmox}
      - {task: provision:create-talos-vms}
      - {task: talos:all}
      - {task: bootstrap:kubernetes}
