apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: default
  settings.yaml: |
    title: Origox Homepage

    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 20 # 0-100

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 3
      Storage:
        header: true
        style: row
        columns: 4
      Network:
        header: true
        style: row
        columns: 2
      Home Automation:
        header: true
        style: row
        columns: 2
      DNS:
        header: true
        style: row
        columns: 2
      Observability:
        header: true
        style: row
        columns: 2
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
        - K8S:
            - abbr: K8S
              href: https://kubernetes.io/
        - Talos:
            - abbr: TALOS
              href: https://talos.dev/
    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/
    - Entertainment:
          - YouTube:
              - abbr: YT
                href: https://youtube.com/
          - YouTube Music:
              - abbr: YTM
                href: https://music.youtube.com/
    - News:
        - Hacker News:
            - abbr: HN
              href: https://news.ycombinator.com/

  services.yaml: |
    - Hypervisor:
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX1_URL}}"
            description: PVE1
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX2_URL}}"
            description: PVE2
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX3_URL}}"
            description: PVE3
    - Storage:
        - TrueNAS Scale:
            icon: truenas.svg
            href: "{{HOMEPAGE_VAR_TRUENAS_url}}"
            description: TrueNAS Scale
        - Minio:
            icon: minio.svg
            href: "{{HOMEPAGE_VAR_MINIO_url}}"
            description: Minio
        - TrueNAS Scale:
            icon: truenas.svg
            href: "{{HOMEPAGE_VAR_TRUENAS_url}}"
            description: TrueNAS Scale
        - Longhorn:
            icon: longhorn.svg
            href: "{{HOMEPAGE_VAR_LONGHORN_url}}"
            description: Longhorn
    - Network:
        - Unifi:
            icon: unifi.svg
            href: "{{HOMEPAGE_VAR_ROUTER_url}}"
            description: Unifi
        - Syslog:
            icon: graylog.svg
            href: "{{HOMEPAGE_VAR_SYSLOG_url}}"
            description: Graylog Server
    - Home Automation:
        - Home Assistant:
            icon: home-assistant.svg
            href: "{{HOMEPAGE_VAR_HASS_url}}"
            description: Home Assistant
        - Node-RED:
            icon: node-red.svg
            href: "{{HOMEPAGE_VAR_NODE_RED_url}}"
            description: Node-RED
    - DNS:
        - DNS:
            icon: pi-hole.svg
            href: {{HOMEPAGE_VAR_DNS_PRIMARY_url}}
            description: DNS Primary
        - DNS:
            icon: pi-hole.svg
            href: {{HOMEPAGE_VAR_DNS_SECONDARY_url}}
            description: DNS Secondary
    - Observability:
        - Grafana:
            icon: grafana.svg
            href: "{{HOMEPAGE_VAR_GRAFANA_url}}"
            description: Grafana
        - Prometheus:
            icon: prometheus.svg
            href: "{{HOMEPAGE_VAR_PROMETHEUS_url}}"
            description: Prometheus 
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""
