---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: default
  settings.yaml: |
    title: Origox Homepage

    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 20 # 0-100

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 3
      DNS:
        header: true
        style: row
        columns: 2
      Network:
        header: true
        style: row
        columns: 3
      Monitoring:
        header: true
        style: row
        columns: 4
      Cluster:
        header: true
        style: row
        columns: 4
      Remote Access:
        header: true
        style: row
        columns: 4
      Storage:
        header: true
        style: row
        columns: 4
      Media:
        header: true
        style: row
        columns: 4
      Home Automation:
        header: true
        style: row
        columns: 2
      Other:
        header: true
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/
    - Entertainment:
          - YouTube:
              - abbr: YT
                href: https://youtube.com/
          - YouTube Music:
              - abbr: YTM
                href: https://music.youtube.com/
    - News:
        - Hacker News:
            - abbr: HN
              href: https://news.ycombinator.com/
        - GP:
            - abbr: GP
              href: https://www.gp.se/
        - Aftonbladet:
            - abbr: AB
              href: https://www.aftonbladet.se/
        - Expressen:
            - abbr: EX
              href: https://www.expressen.se/
        - Readly:
            - abbr: RD
              href: https://go.readly.com/discover
  services.yaml: |
    - Hypervisor:
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX1_URL}}"
            description: PVE1
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_PROXMOX1_URL}}"
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
                node: PVE1
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX2_URL}}"
            description: PVE2
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_PROXMOX2_URL}}"
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
                node: PVE2
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX3_URL}}"
            description: PVE3
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_PROXMOX3_URL}}"
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
                node: PVE3
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""
