apiVersion: v1
data:
  HOMEPAGE_VAR_BROADLINK_CONTROL_url: ENC[AES256_GCM,data:ASzrKg==,iv:TBa0Dyd4kMUebr+oGE4wQhyAE5BYBcFFw3WW9uvNnAg=,tag:MbhqN96EQnkzCHMy577PRA==,type:str]
  HOMEPAGE_VAR_HDHOMERUN_url: ENC[AES256_GCM,data:CDCn0A==,iv:gcYAM87odvwpTIESFvoGdvuXCAPf09u+63B+3cbeWh0=,tag:H6QU8HfdOKJpciCSH6X/bQ==,type:str]
  HOMEPAGE_VAR_HOME_ASSISTANT_API_key: ENC[AES256_GCM,data:VddADw==,iv:ZiNM8Yt+9uqPKPMuGyo/qW4YRmyyroxiDYjdAhUAWmc=,tag:NWRZI2ETACB58j3lwdueCg==,type:str]
  HOMEPAGE_VAR_HOME_ASSISTANT_url: ENC[AES256_GCM,data:6zzefg==,iv:Ruy0OOwLjdgQUnMkhvE8nGSsn/Ksm2F9qWwOGvZDNUs=,tag:TyVrWDd1vpwJ7cas0ml5Tg==,type:str]
  HOMEPAGE_VAR_IPMI_1_url: ENC[AES256_GCM,data:zW0X1A==,iv:Of9AOt1B1EW/OhQ89/Ujy55YuoCTfH99bPckSBlbIXI=,tag:70tuNF4y++zBbQNm1XSZLw==,type:str]
  HOMEPAGE_VAR_IPMI_2_url: ENC[AES256_GCM,data:xOYUSw==,iv:zdR8iHZSqhf2ORnmstarG76EpMD8dfFv8e6OQASldAc=,tag:OiarJI5pvh3G41uyrg4RiA==,type:str]
  HOMEPAGE_VAR_LONGHORN_url: ENC[AES256_GCM,data:p+6XtA==,iv:V51Ju1wkEArHM0j3F2q2AX7o8cFSyQSuy3bNjfz01EE=,tag:INBpESlUm0/53IHHkTZSPw==,type:str]
  HOMEPAGE_VAR_MINIO_url: ENC[AES256_GCM,data:j2481w==,iv:xM+mOPMG+sYiOcEhJWvcZ890clw3Dqn8bHDYPP9BQVk=,tag:kn7HaAm1+WZQrbc6ZvkBYg==,type:str]
  HOMEPAGE_VAR_NETBOOT_url: ENC[AES256_GCM,data:oFjLRg==,iv:cEoNFqCl3MCjJxCg8RD4i2IVzGjFqtLOtlqO7OosJ98=,tag:nTdFpPqh1yecoa71YEp04g==,type:str]
  HOMEPAGE_VAR_PIHOLE_API_KEY_1: ENC[AES256_GCM,data:9d9Zqw==,iv:sb5/oGocPOvItJJg5Gp15Sk42AflIho+V4VTn/TVQfE=,tag:0daCfuFTMXNvxK8rGpei6A==,type:str]
  HOMEPAGE_VAR_PIHOLE_API_KEY_2: ENC[AES256_GCM,data:5DSHQw==,iv:yD31PEpzZRp7kBIAfVYppRqD4j8LBHllXq6I4xPURHg=,tag:kOkIg/S7B9/VaWwjZZqmWw==,type:str]
  HOMEPAGE_VAR_PIHOLE_API_KEY_3: ENC[AES256_GCM,data:Y8AIKw==,iv:gJ1uL93gWtq9P3xaJGlrPWoIefwFRdznRZwdZbwd83s=,tag:Qfj3nh7m9qYJs6oa70lIqQ==,type:str]
  HOMEPAGE_VAR_PIHOLE_URL_1: ENC[AES256_GCM,data:B1EIhVu47L8CEVca56zQTbYyXC23vlSFU4a1a0VUZMaZ5gYKjiMk1RUgrn/AayrffQhiyA==,iv:kFgEgZkwMZ75gEFglDR0hGaNpo4orLNoenQevnHzTC0=,tag:rFgYhDQZi9sSsfL8BDy5fA==,type:str]
  HOMEPAGE_VAR_PIHOLE_URL_2: ENC[AES256_GCM,data:l+KvAg==,iv:L8ZabWOMO13m7HCOuF5TrwiX1SgcLr3Ey+0FrLdlmXc=,tag:aRW6U9TmQOKLSXCEeCE1vg==,type:str]
  HOMEPAGE_VAR_PIHOLE_URL_3: ENC[AES256_GCM,data:7sU7Ww==,iv:v8QCKPJq+2P0QjgZNTzCy9kt7+dpTlXGskZy7aoNjvs=,tag:cTILznjPwFxVUX7EWfjdgA==,type:str]
  HOMEPAGE_VAR_PIKVM_url: ENC[AES256_GCM,data:EFSoeA==,iv:3yzCb+rj9bngvZJuojP9Fa5mmJMs3CwmPKYulP85OdE=,tag:uLSjqQ6LJTHya73y4b8+qQ==,type:str]
  HOMEPAGE_VAR_PLEX_API_TOKEN: ENC[AES256_GCM,data:w7b7Vw==,iv:+caieJiFftDuLMlyQ/c/El1oHLP109oRpTNTIX9Ky58=,tag:5+xe8bBVrNdo/oxhScWCbw==,type:str]
  HOMEPAGE_VAR_PLEX_url: ENC[AES256_GCM,data:zdJ+nQ==,iv:/lbcah0c6y35/K46m5KcLo65mUXYqf3vep2HJagyYCg=,tag:UQMq9tOUtpSwaPi/Gasyqg==,type:str]
  HOMEPAGE_VAR_PORTAINER_API_key: ENC[AES256_GCM,data:1NoY5w==,iv:+TMbPxfy0Kbvch0LX0Djy12vuwhhZOPmVMFohslW/Lg=,tag:UeXP7mwEMPrDHYkw3IalEQ==,type:str]
  HOMEPAGE_VAR_PORTAINER_url: ENC[AES256_GCM,data:bIWjog==,iv:C5nkUH5bRzHgs1AbQJOv3OiqFF3GXdNXdBECTzH+OBU=,tag:JgTOHG0Qj+5E/Ytt0LCbng==,type:str]
  HOMEPAGE_VAR_PROXMOX1_API_key: ENC[AES256_GCM,data:pRE3vPnOaWaC4MfYI444xQsYq9nEwTAc1rsFnUH1ceFcwzQ0AC+XcuGa3ijq24ty,iv:opKtY7G0f7PVZidQNGLoq2X9Zn5kb4Z0FQpB1KGcXO8=,tag:ZxqxDD9lian7Dcj5likXPg==,type:str]
  HOMEPAGE_VAR_PROXMOX1_USER: ENC[AES256_GCM,data:XAkMiMhOrJQsO6RgtB/Ugjwa1Rk3PTGjnqa50w==,iv:dmboAMcrLa5TYTBVl+t7QTNmqcJPtAcpaF0kbCpGh4U=,tag:qCg/64HBtf0sKrfHszaypQ==,type:str]
  HOMEPAGE_VAR_PROXMOX1_URL: ENC[AES256_GCM,data:fyuqt5BHTAm0DZ4ULPBUqsOvaPpwxKDz746cnaBxP7La5nftj4f/s+doz2gZ+l5ARQdVAg==,iv:myb75AUAjG9twnt3bA86RYiW8hu0jy4CUb69KH4NiIU=,tag:CSqGVE36J6N6CfP1+HuiUw==,type:str]
  HOMEPAGE_VAR_RACNHER_url: ENC[AES256_GCM,data:byUltA==,iv:57c5ylJJd3K9NjNemyfu9L08KDIXVmY15eNYk6KRo4w=,tag:Ki5y90d7N5dDfRTo1vxESw==,type:str]
  HOMEPAGE_VAR_SCRYPTED_url: ENC[AES256_GCM,data:W6fklw==,iv:X282kpWJVO9E4SqZOSeWKQ9LDsDbULU3gufkbZPMU3w=,tag:P818YM2g8NmBLtEwqFP9XA==,type:str]
  HOMEPAGE_VAR_SHLINK_url: ENC[AES256_GCM,data:P1u4Hw==,iv:Odif86NL0FW0W+BfGaer4/G+VpJYGfMomohGILkjPAA=,tag:JdkYzmmp+Lr89l10zikJoQ==,type:str]
  HOMEPAGE_VAR_TAUTULLI_API_key: ENC[AES256_GCM,data:EWoDcg==,iv:rDmJe5kAQBPFCui1/uNvvxnCNPR8C9N8IfJt1KyiN7E=,tag:nMPbKQx62gsqe8LTMfsSzg==,type:str]
  HOMEPAGE_VAR_TAUTULLI_url: ENC[AES256_GCM,data:U164uQ==,iv:DfpfFlpuvpGODwihMu4hgnZreGq+UiVwV+Sj1GtUDgk=,tag:SJ4aeMDNm6nzACmPqETw6Q==,type:str]
  HOMEPAGE_VAR_TRUENAS_API_key: ENC[AES256_GCM,data:lBbKow==,iv:h9kFwSGT8hg+xgLkOF3c23gAi3qf96xd4fA0tUFvIJw=,tag:2Gc4bFsGPp3MUsV19iiq9A==,type:str]
  HOMEPAGE_VAR_TRUENAS_url: ENC[AES256_GCM,data:b8PoZ33HRUrE03+AhPFax3TgD6qrrN8gBjPr4HU+dmrkhmj51d2GXbXnBnw=,iv:bjEbYdbtQ1pYUF2Wl4MO8IX/uG4Codhr8f3ugiNndHE=,tag:niACN7HQUlChUHGJCgm6XA==,type:str]
  HOMEPAGE_VAR_UNIFI_NETWORK_password: ENC[AES256_GCM,data:bdU9lg==,iv:6sWINJ4KRZUnKBfdoLJblPs4Zzf95bDDqRP754x4AA4=,tag:5vphii2JB+PWLSRp7pCKCw==,type:str]
  HOMEPAGE_VAR_UNIFI_NETWORK_url: ENC[AES256_GCM,data:mI5TnscvRh1Hni1BkgipfXNX5hZceRZAh68Qs1+TtrRuNfkuFNxvcnjfPPCYfJHr,iv:fpsljkpe3/TBhWNwb1fHgDMNWq0STKH1rnz/kIUMQOw=,tag:xf7DkCK1buyx8iV8atmAbA==,type:str]
  HOMEPAGE_VAR_UNIFI_NETWORK_username: ENC[AES256_GCM,data:9QXIaA==,iv:PfsVDTMC1ivc61dkFwefkAAxVKtyAS5Vd26E7JzMo0Y=,tag:aukd7ZJCc8tZh6IS9fbfng==,type:str]
  HOMEPAGE_VAR_UNIFI_PROTECT_url: ENC[AES256_GCM,data:gryK5w==,iv:md8QKicv/7THwkyefD0hOrrTQKq4EoJJSNCqW16w/zI=,tag:v5wgRKhDWdD4hanUDX8oXQ==,type:str]
  HOMEPAGE_VAR_UPS_1_url: ENC[AES256_GCM,data:s2oosA==,iv:ehCSh+jeoUSuZ+nMM86ajtkzR2Jw4uaz+bCKFG2cwmM=,tag:8FEwe0JoMLiTuNDCT4DY8g==,type:str]
  HOMEPAGE_VAR_UPS_2_url: ENC[AES256_GCM,data:pVXRUw==,iv:gEBpbm08eco58yIfna3NJlkKAjgwLA+kLq/QIxR/oDE=,tag:QZwp1cMrbGaO7oB1jinaGg==,type:str]
  HOMEPAGE_VAR_UPTIME_KUMA_url: ENC[AES256_GCM,data:UC63Xw==,iv:K1Sq5OMX6X878pF8/B0x2Fy4uex8KDctHZ51k+/P02o=,tag:kCxn7ZxjTHy+8CMkd2zV1w==,type:str]
  HOMEPAGE_VAR_UPTIME_ROBOT_API_key: ENC[AES256_GCM,data:9Xq/OQ==,iv:JmiEd5Tyd1KKlZ7n4Mx968bkNvqOvkBLprWA2sAWFQQ=,tag:YOUQwjLh1Scc/9sl/DGx1Q==,type:str]
kind: Secret
metadata:
  name: homepage-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NUYyc1JFcGJ3bDFscGdR
        eWIrTC9HTDBxNE92ak1SZXJSS3A2cWlPcUFNCklOeWk0cEt4V2RrME5YOGczNFF1
        c2I5NkZ3NEdqL3dDNEczR0xydXdWMm8KLS0tIHduMHcrUTR1cDdRUUJSVTdXSGlD
        Q05xdFdnNmZLUmJFRkRyVmJNaVBLU2cKZvxG59joTasPRtoc1FDEhQKYIGwL6HpF
        cDf4QnTFuPyHQaWBI+XPx//Zj0y3dJMYUdFfwhPTzre+0lZCJjC3ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-03T18:45:48Z"
  mac: ENC[AES256_GCM,data:Kh0JCHucHAhXD+JybHAA+HJxRsGhhZ3P5L8c7i2CZ4RZ7TT59GU7l+dayNckdd6uZ3GJZD9rj36XPJlAzdDy2lyRGvSqxkpvRtK2nk4EQBQe9T0AEJ2US/4UBSRQP/xrRAhNIJ+0mWxv5YQ4xPAftkQPXXqWEPz2J4mEHbW9wyU=,iv:IyxTgy8imqbT0LUXfSOgGRG4ZvOc0Z/j9hoexRguSRQ=,tag:0YdYlGHCamEXqkIf2ZXUCg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|ip)$
  mac_only_encrypted: true
  version: 3.9.0
