apiVersion: v1
data:
  HOMEPAGE_VAR_LONGHORN_url: ENC[AES256_GCM,data:7lzg/h7aOeOaVVkd4ZXsXDvHkeMi7wnfCxvmePxOYpFmLdocjfxMVhoPjPBVCjmZsC+i+A==,iv:9hos0GDtKKDafaC40RIvPyuU5b4KVk1L5GECguYoJ9U=,tag:IBpSnjEj8XYYAVu9r4tFDA==,type:str]
  HOMEPAGE_VAR_PROXMOX_API_key: ENC[AES256_GCM,data:dO/Oao4skNzDIWw72Mts/mLtpznl4ZZg2tuIctp4JeTp61Bq3VHrkz6q4/h5VF4H,iv:zoIla7MtbYPrMV06irZWXgeT4kCSMA+HqilO3vsoLuU=,tag:L3vI+usHWyDbzUsCS3zyhw==,type:str]
  HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:tcHOGO/2yLSvQtNw1JbIzKvm+IG8SIqYihTP0Q==,iv:La6JGvd7242mmYhi4lGXSIaWj7vhrneBCpDnyVCwelc=,tag:cBmUVlVcjor/diw+5r9Kcg==,type:str]
  HOMEPAGE_VAR_PROXMOX1_URL: ENC[AES256_GCM,data:io6uVP5u7mlC86B0ud7FwTUwiHHA6mLdYjifPmB1pbvveOMfgZyJq+DypoZxp2yl0bnNmg==,iv:Z3BR6M1ztJSefVPnqbKnmZFjD/9jU//f3kFNUXHEf3g=,tag:MGNjHs1ugsjTGlkebKxcjw==,type:str]
  HOMEPAGE_VAR_PROXMOX2_URL: ENC[AES256_GCM,data:h6jpxXOGTLLNG203gtx7uQHqkKEoyGkRZZBTCdlPN2mugoCbcdmmZJqxq6fe/cxtbQvYRg==,iv:BT2p2VMoQpw15glBCWhB1c2pXqW2L0yt9qhLU3vjTJM=,tag:uFmlcrNyp/CJHOZ/LpKOSQ==,type:str]
  HOMEPAGE_VAR_PROXMOX3_URL: ENC[AES256_GCM,data:0kdMXArn4T2IsYztNIGpzkF/C6ooPqxKyeaSIclzbXvyI2t8UnJ/LpPmObAQvlhcdRJA3Q==,iv:ZSq9zBasvf3yCExDPg1EynHHNXATJ63Vk66UU9AIPpY=,tag:1BX7vlfBz1K/Uxod6ZaWOQ==,type:str]
  HOMEPAGE_VAR_TRUENAS_url: ENC[AES256_GCM,data:YUBsisY4SUBQaN6MWuvUbCXn1Y0VXi8VzEsgM6ka0cW6BTuc4E9PxK2II1KsZmChS2lnH0HJgZ3YHXJx,iv:AbUBuFvhNAdgLDo6q4fO7FHVcAYwP+BHd88ZhfgxpRs=,tag:gjG20309E9gu7oE2gHoh2g==,type:str]
  HOMEPAGE_VAR_MINIO_url: ENC[AES256_GCM,data:pCVuhyptcY1UXpRt/eqMRIp1cFKu6ohafkAYYn2RTH+1lgcSUdgfojqCTaqJ0Y4bYG8MQQ==,iv:JIqLTBD42K8iLAGZP5sp3M5j4o6Ya7/OGOVKo7sZG30=,tag:WMADB0+5AzznrXk1isLimQ==,type:str]
  HOMEPAGE_VAR_ROUTER_url: ENC[AES256_GCM,data:iHT7dp3g/rUEWC56ShNq8zo1pPSueDSEaYQUuoEJSTObpnMQdKBimHEvKOI=,iv:6nB9Sj266QHy00zz2FO3a9PfxQ0CASh6izaseRfFeiM=,tag:Iy66Uc8WHOsINSJOSYG3RA==,type:str]
  HOMEPAGE_VAR_SYSLOG_url: ENC[AES256_GCM,data:XiUBFumofbLtx9jxnLiVBkK41bLqN5gJJagh45s42Mj0XzQxVicaYfNL1DJ/ve8poQ6n8hCWolueYDuG6xvtQA==,iv:0bxQUFZ7k5Y7zi4zAV6IqUAmZ2fUFLjfrugtPAyPQOQ=,tag:aNfbyRXoBH7b7f5M7v/C5w==,type:str]
  HOMEPAGE_VAR_HASS_url: ENC[AES256_GCM,data:gdf8b61HE5QW155bF2D1fb+3HNVrnH+FQxtXEbmSFZF4vP7mWZqy/iIb61hWCM02,iv:niGoKB2REOwpeyQRdrW2XcFHl4d6OSQtNjqHhAoD1X4=,tag:BxxsM9db8stz5FSKP97/kA==,type:str]
  HOMEPAGE_VAR_CODE_SERVER_url: ENC[AES256_GCM,data:ltc5JMPg1qMHgpRVZm9WB/X1cpPHK76iiIn+o2NqtHtMmt3ZFGG0uiRt8q5LhjGgFPKbcNmF7P4=,iv:y5ZtODTAEGPwnWdPoP2ROh6MGZ4uvmIL8AL1kVch8eQ=,tag:Litl8pyIZJrw39IVMwr22w==,type:str]
  HOMEPAGE_VAR_NODE_RED_url: ENC[AES256_GCM,data:U31nP4ZEjZJZjI/CEo0uoB2Xb8U5zuSmkk+2zV71D3MeYDsuhwwu+n+CxB6b0ImwOzsh8g==,iv:13BINkV6F5KHTSK4MUMRTFSsN281Lb7ssiKjlKNwNgA=,tag:3Rkp5Ua7wJqbYlf/vfffYA==,type:str]
  HOMEPAGE_VAR_DNS_PRIMARY_url: ENC[AES256_GCM,data:n5Tb4aqi07ssVKpVhse7NivOhgYml6uZGzle9uuZGKG2nwpyMBSnaLNJ6ULylNy7kG+eA2DYy8+ae8+IaZQtew==,iv:IZNnmPLPfPujLGAP10HRW8spZoYtvD2YW9lPATMoIfU=,tag:YzXYyTjlHt7ugnWmCOg4kg==,type:str]
  HOMEPAGE_VAR_DNS_SECONDARY_url: ENC[AES256_GCM,data:cCKEIKr6RCDU6Z4XBNqAO/1KyOAz7UDhHL+Lmtn9H1kOWeLbZ1g/IjbFqhWBK1RTDilQK3rs0Rs7nHhcoJCbwtBcLuBHl1+N3+lr5w==,iv:aPOKNUoSqsWsL3w8mDxlx1tmOjs9WV50gjd8Cnm2N4Q=,tag:PChVIYt/J7D7jxHAecDtLg==,type:str]
  HOMEPAGE_VAR_GRAFANA_url: ENC[AES256_GCM,data:0H3sacaqdXCcZNY3Dc4DduVNijeUu+NBWLkU6sA55wV15YxncPWgoNca/BgovLOkbUhaDg==,iv:sfa+PiTzAcIX4T2XXQAdLcd09qtnm/mkssPQWYiQnOA=,tag:bl3bNKg+GtzJ8gdcUA/46A==,type:str]
  HOMEPAGE_VAR_PROMETHEUS_url: ENC[AES256_GCM,data:qpHNauxgL1c4xGc7D76F9Vix+59+hf0q3tlEzvXprXqRgpi6waRfgYjlVMgI3XPTKGlBsXoTTM0=,iv:Xyh+71yQWSdUfSnavIwAQGSpKj4vHVJBpY6XAaRWLkY=,tag:7tS4xsmLpXbk/CzNfCVmxg==,type:str]
  HOMEPAGE_VAR_ZIGBEE2MQTT_URL: ENC[AES256_GCM,data:Bx2g9SfxJtCx06aezebfNmWY7cbfCx7MG+5Js7Cr2BwSLFL1TL7mF+JbthMTNu6ySQ8LJojFShA=,iv:hWnIlAEh4hvVEHKJwhqxzcrkCj4aenk92RWjhB9+MEc=,tag:sNoW/HhaTeS4/l8g4vzwSg==,type:str]
  HOMEPAGE_VAR_ALERTMANAGER_url: ENC[AES256_GCM,data:CzU5mTSTOfqsc+ExxCTjV81nD+wO+0fvW8p/QeaSbA8kbYIkTUICrBcRyFkQTJzlIT+8I8NVmcE=,iv:HMGmY1QCtjruNI2wfjiuWH2aBiqMRDKlkSC1dD4qNag=,tag:AomwvmlUIk+JXyAkAMQ2Hg==,type:str]
  HOMEPAGE_VAR_INFLUXDB_url: ENC[AES256_GCM,data:5G7cKNxFfcUaim/GFN63dTx1s6yimJj47rx/D6WS0k4T0X3r0XuqPmY5y5J3EyJPDWQhGA==,iv:ZEFMFYZRw+YWm49s2Gj1JtxVix1zeppsQVoV4Jq0caU=,tag:YpYi73kcp+h2UMZPTUGLlA==,type:str]
kind: Secret
metadata:
  name: homepage-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxL2x5RUNvSmlSSGxSUGxt
        NVlxaXExamF5WVkxR3ZYOGtpdlJPbGZKd0hBCnYzQitLQ1Jva1JLdmlQamRxODNa
        TE5aVGtObm04RVVvaGZqQUlLOHpHbDgKLS0tIFRIWDF0QzlGUEUyWmhKbytmb2JB
        MTNMdWlBRnhqVXMwVTA2ekhlTWducm8KltfMc/1b9nWwg0Q0WLdFKVstf3lHT30Y
        tED5Fk2obRdDpknbfypK4P/S6GXOTrpvO1nyMsfrB0p70RdLlBXI3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-13T18:47:26Z"
  mac: ENC[AES256_GCM,data:dWg6EII5O6LBOBOnDWa357sum+0PLAzDPV7YNEJJpQX+uuXk3nA0m5/L7Pdp15WK9Tv/aOuApNR6mHYmNfL0tGNCIB+EvXWrxyfM3RnIrtEBl4Gb3xSGm4klsyEJgPwliGmsPmSJQI4mQNPnbMPx0Qf9dv7RNySTwE4+tSspTbg=,iv:lg7/Y2eRVz+EfAG67HyszCW8d+m0mQJDtE/4hj0ydcg=,tag:Gf2tpYZhHAAE/OLAo3Qo5w==,type:str]
  pgp: []
  encrypted_regex: ^(data||stringData)$
  mac_only_encrypted: true
  version: 3.9.0
