apiVersion: v1
data:
  HOMEPAGE_VAR_LONGHORN_url: ENC[AES256_GCM,data:Lzytbo6oprXQl+RfyOFLZBtE+oD1v70yFWfGsdSpWx5i+rz6aEXBROM2UGL9AwZKZw6gXQ==,iv:ssVWL5suYotBNWiJv6H9FY3rLrbzcusND2SAzrsrq4w=,tag:Di5KHZfkOUnpmIrS7mryBQ==,type:str]
  HOMEPAGE_VAR_PROXMOX_API_key: ENC[AES256_GCM,data:0UbDR908Oe5pSiTtGiUH/3vnDdtmeu6B5DBcpdMtDS2dK3NbczcF1cwG2HsPcPEl,iv:0PENr/y7eYAmDUTW/Wp7nHvqIHAE3g+xv2j2N0mtjOg=,tag:xH1ubi03hP+HJ5gTMP1aWw==,type:str]
  HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:h3oM0wO6U60czxswsfWAT82CiQhAYoXGxP8D3g==,iv:zGRnzUfZjphbqiBcakP/JqLz0d8aqUVG/Ucb7GsJJL0=,tag:FRpZsWrshGU0JZSOpT9dhw==,type:str]
  HOMEPAGE_VAR_PROXMOX1_URL: ENC[AES256_GCM,data:t8254m1l1Us2RkWLHE26z3RdEPXRs605eQmBqPpNi0TqzoxzU+b5+fKVJK4eWw2rz6Y/Dg==,iv:wr7SmNbOkPFnXlPAh8qHeKUBBX8gy8APZCiRhPDTbFk=,tag:i12/nk+qqTShusuK1iQA3w==,type:str]
  HOMEPAGE_VAR_PROXMOX2_URL: ENC[AES256_GCM,data:vRy478G2Q6tWi5ujKNrAueMUdITeESAL5IerXmoUVrr1E8RIlcY3eCClTs+ZCGkiCp7xpA==,iv:WCBEiexweEOph8dGwbV0gBerCiQoNe0rLrcLw67JMw0=,tag:FaD+g+aQiZFuDeo+0Ac2Vg==,type:str]
  HOMEPAGE_VAR_PROXMOX3_URL: ENC[AES256_GCM,data:Gvt8gJB4oEUIKalrn/uHgjNaSItb0tLjV+m6BfX1Pihz+2FHKcARg2le+L7TC3Q7lXGO3Q==,iv:NLATEoHtPsQiI4miYaabQJuHE3XoJgT1VjlCtJh5nwo=,tag:f23Z9X0br5RLAQbA0h2eww==,type:str]
  HOMEPAGE_VAR_TRUENAS_url: ENC[AES256_GCM,data:YVW1hsI1DYUKAdY7UHJ+4MTSiy5Rtu9bJYvABKcJeZ57hjeHE33F15RLHDuVjDmKtEvcXkiTXIYUA2oZ,iv:iwnxbIciNJ4AMa3+OmtAquYXFRAYhvU/0FqcVvFZYjw=,tag:RXiBfSrJdKjGuzkErVsdsQ==,type:str]
  HOMEPAGE_VAR_MINIO_url: ENC[AES256_GCM,data:71h74KKvx/zGTZ6DO8vuWpdad4yxvVOSrhcPtfl9xUWEO9zpr+cR2IV2Mxxx1H+w,iv:p9CgiMgN4w1FhsjdF3Xsh5SZzY8GvSCf8putGXGvspc=,tag:Gdruz9OGJT9dckLwA63e5g==,type:str]
  HOMEPAGE_VAR_ROUTER_url: ENC[AES256_GCM,data:X3dMtYV6eK5lwk3vPOqcvBUyCO45s3xMxAQq+OYIy+Hj/2HsQmunXZ3JZY8=,iv:mcNiUu18T1c32C+eAOAD1Q1hgehfXKrbzLC+DuSM7hY=,tag:SQUJBBBcNtVqqKZ4wf6u5Q==,type:str]
  HOMEPAGE_VAR_SYSLOG_url: ENC[AES256_GCM,data:VeNV7xeWDMgg1CF7L5NHrOAs3IGj/CBMp0yXYNFp0qefuC3tg24LrGqpqCO/H25n15WADlS/3RdoN+egK4BLOg==,iv:tkVbAuorUn3ljYv+/G6viYstfesEIJZAfG4vxFA0zCc=,tag:4noaOJsDpn34uNmmXQLBlw==,type:str]
  HOMEPAGE_VAR_HASS_url: ENC[AES256_GCM,data:kcRK7T4rGWGfGyphrA9JwctI+61sGhW8tRTRbhFKls0VnduRF2tHw2w9EfL0Z2swYjULJg==,iv:dTLjDwOfXS8Dvg5HeTjTRBXlt0kNtlDstR+BROaM6OM=,tag:PY8RDxN3R+XPY09LE4qkmw==,type:str]
  HOMEPAGE_VAR_NODE_RED_url: ENC[AES256_GCM,data:mEzglz4gEV0JDQgPiELR1tbI3pCda0uCnctIQhvmPcIJakj/cfwrB5j5RrJ/kKiJ,iv:aVbqTTFOR1a9tyQqZ6cGFo5SuJryDxZrtagaqMB6ORw=,tag:jo/Nl+zh2uEW/kQb78PMig==,type:str]
  HOMEPAGE_VAR_DNS_PRIMARY_url: ENC[AES256_GCM,data:UhSxU5oGfUFrTaAxmXBiNte1HW+yc57Us2dMnoClyUAp98cbxBver/ZhzZ7cel+kCkhZ6cLLAiFYBYB2nyIeNA==,iv:APmcOm9BaV7roNqUOlf3BsL97yULyTlQMPX//F5/MxM=,tag:XTBqD838Zvig8+5+FzyU3g==,type:str]
  HOMEPAGE_VAR_DNS_SECONDARY_url: ENC[AES256_GCM,data:kjgJvzOWPIoySffE6JLPMptHEnfyFObwQCRbYoVwmzAcWlBV6OBD4O/JoNS0LL6n3T1DyVhyj16+jyKVKXyYbkZYRSCbDUkGIdLdrw==,iv:tVaN+rVRZf4SqEQFg542i/Q7wD2xrmWwHeER3GJEPiA=,tag:cMsNfMz0Wk1OD3uVFts83g==,type:str]
kind: Secret
metadata:
  name: homepage-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPL2R0aXh6UG1oQWVya1BQ
        c054Znp3ZHNsZHV0RnhNaXZaUU92dnpZS25nCjRZdmE0akVFMjFUQk5WcE9QNXlE
        TVpTQ2VLNHJyQ3UrV3psU211QWNMVkEKLS0tIDd2NnhhZUhKd09lZ2tFWUhGL09J
        ejBoMnYydjZVdHdzdmw0Y1AyVW5ZUWcKseQFeganAASokcsV+Mc1DL6KaGXcksbC
        pKr+VoIRcg8a1xqe/LeHFcMriJ8CiEeYSxh9Wp4pS0nh2VCgQVtFUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-05T18:24:07Z"
  mac: ENC[AES256_GCM,data:8cmJOffKjTecdMENSrVe40tEuRZheAmAksRBsONMx4Kne/uIUDB6eat0zzRzz0MHkVlkgZrVs4boIxVFWWTuonKwfgPsm6OpgSIW/l4yLEMBcu31747/b2bQBjZNrZ7hzoyJ1lmg7qu1aPe5itO6HQ4Bgrkf2xzS/tBXpQ+UIuA=,iv:2T2nzndDrS8vbNsjvqQUlJX53zIJs5s79uZtp5o0VPQ=,tag:saQzj6FQbnHZx/aVpNgK/A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|ip)$
  mac_only_encrypted: true
  version: 3.9.0
