apiVersion: v1
data:
    HOMEPAGE_VAR_BROADLINK_CONTROL_url: ENC[AES256_GCM,data:vxQ9XQ==,iv:+lox6jK6n0gdXFZO9EXOlKnFkIotNdZ/wGE36TEWCGk=,tag:r83flWhr/9lg1yL/KFw2Ig==,type:str]
    HOMEPAGE_VAR_HDHOMERUN_url: ENC[AES256_GCM,data:eDMXZQ==,iv:qRPKNAXxSQBA6CsPAgTJZCYuwcqv3Oca1gW+zR9Woqk=,tag:qGGw8S3m/YZp8lMTrmJ9xQ==,type:str]
    HOMEPAGE_VAR_HOME_ASSISTANT_API_key: ENC[AES256_GCM,data:Ns2unw==,iv:32pHoP/+8YJv3L4riO/SKtwxguvhIMGM2/bc/g2GlYo=,tag:utNC93P9j7YRp6q3zwlFcA==,type:str]
    HOMEPAGE_VAR_HOME_ASSISTANT_url: ENC[AES256_GCM,data:icKUpA==,iv:wUa40rkwQUk7EHK4cxeTsicqH2OKNtcosLe4jd9YDjo=,tag:0WEpPrLza9QonlIlyoFpqA==,type:str]
    HOMEPAGE_VAR_IPMI_1_url: ENC[AES256_GCM,data:xWS2pQ==,iv:JWcmLueaML8pN3KRIFCnxBKD8Vz10JmqSZiATTRy5q4=,tag:CDBrezUt/+DaeOgoLNVeBg==,type:str]
    HOMEPAGE_VAR_IPMI_2_url: ENC[AES256_GCM,data:BUWuqA==,iv:GMu8zTLGpZwE3CXHAlvWh3ep4VJLcivgFCAT1B3nKQs=,tag:v4KFg3n9FEHzEdXUvvl8Ag==,type:str]
    HOMEPAGE_VAR_LONGHORN_url: ENC[AES256_GCM,data:8q6lYw==,iv:KCR2CuR918FgKYy9Vl/UJ9uGFt18Na8U05LTnnhyinM=,tag:HgQDKIvqK4BDrYy/UmQLiQ==,type:str]
    HOMEPAGE_VAR_MINIO_url: ENC[AES256_GCM,data:mq0Rqg==,iv:vSjHvicXnN2OEpqpMUEGIKasQf415dZe9s+X+rWosaM=,tag:8+bdiM1sNaEiEoKAEO3S3w==,type:str]
    HOMEPAGE_VAR_NETBOOT_url: ENC[AES256_GCM,data:fWU2KQ==,iv:IQALiBdiK9reQgJeL7OIYhUKR3Hr7Z6foYRGfHTci3Q=,tag:RNDLC00wHWlUcM3txgMLDQ==,type:str]
    HOMEPAGE_VAR_PIHOLE_API_KEY_1: ENC[AES256_GCM,data:tcPOtQ==,iv:H8tlAgf0/n5F4nXT0xjx2b8ZV//Y/owimLFtRmCfEsc=,tag:iwBtowC+XExA+DBrgYwovg==,type:str]
    HOMEPAGE_VAR_PIHOLE_API_KEY_2: ENC[AES256_GCM,data:EYxA4Q==,iv:oEGZGFQ831IIyS2twxGjuhD3X+mJgH59iK7uYDLNWLE=,tag:bGrdyu8Ucn1PaknQvcnd4g==,type:str]
    HOMEPAGE_VAR_PIHOLE_API_KEY_3: ENC[AES256_GCM,data:N+qvYw==,iv:I1/+v8q56WkgGTz+OA8iDXHeYUdtH+G1R9UkjXBGCR0=,tag:o3z9+EZcBJfGQOOgBm8Ogw==,type:str]
    HOMEPAGE_VAR_PIHOLE_URL_1: ENC[AES256_GCM,data:7cddwfGxxZDKb9rGPDf2H4naRx5u9FHjCkZjGKZXm19lr+Id/gxK3mCzewg5yS1q3DfXdw==,iv:9256FcD7otcp/RqdwRqcsZinVpjoLrkyIXAUJOOJSYM=,tag:481IEVzomqLvX8b/U6hWFQ==,type:str]
    HOMEPAGE_VAR_PIHOLE_URL_2: ENC[AES256_GCM,data:2jV7PQ==,iv:uKqcJKs1iQ5I1kPnDihIFYWe7g4dAYqtlsMOSRgFTbA=,tag:U1S//pPO9dlw3g2pJ1HK4A==,type:str]
    HOMEPAGE_VAR_PIHOLE_URL_3: ENC[AES256_GCM,data:GEFW8A==,iv:vd3ont0nsnF719uqDQS1FDYfO5T7XqJwmqmBKwkSdCU=,tag:dnzm0nCkwDEJNevhsYRWXg==,type:str]
    HOMEPAGE_VAR_PIKVM_url: ENC[AES256_GCM,data:bX8+8A==,iv:GC9kHcE6r1aRHQ+TtKn8tgaPcX28ewjjP4l+dsysQAI=,tag:7f8vCyn4Z4TqnadMNjkUJA==,type:str]
    HOMEPAGE_VAR_PLEX_API_TOKEN: ENC[AES256_GCM,data:cR+Htw==,iv:lA7xL+nrzQOGTzDiLBfiF9XOamvCkKx+uLJ7wV8IT6E=,tag:wgKs1XbUdQEvzSU9EoghVg==,type:str]
    HOMEPAGE_VAR_PLEX_url: ENC[AES256_GCM,data:Fd5oJg==,iv:DF9CProO7dzxFbMoLjG5HQlbNmyn2jo+LUz6dc4lgvo=,tag:GkW3NyeLJIeyb+IVE1T8tA==,type:str]
    HOMEPAGE_VAR_PORTAINER_API_key: ENC[AES256_GCM,data:CAhtSQ==,iv:JvYn5Dap6jc9FbKFXxN8VonIxcSCY3Lyc7acgImrZyA=,tag:HI7bUbgiLCqR7JnsAJXxEA==,type:str]
    HOMEPAGE_VAR_PORTAINER_url: ENC[AES256_GCM,data:37/sQA==,iv:ruQOT1YC30C9k7eTiodY4kQBoDUoxZh3LlODYWlJz5Q=,tag:rVb9VBWv+9NGLBhTA02y6g==,type:str]
    HOMEPAGE_VAR_PROXMOX_API_key: ENC[AES256_GCM,data:s0jF5A==,iv:PH7QjW4FZf/AINZOeAOzD5UESjlgIvSsM3pyU2BIGoo=,tag:wp4g3cPhvero2/eLV2hGtw==,type:str]
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:VMo00g==,iv:if56sIUG6KCwQPZkbgWESj0SWNkmqlz4XnZz2Phn6zA=,tag:Qp3+iWyGX7dksLYJqjIryQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_url: ENC[AES256_GCM,data:dBEZxw==,iv:7FY2NOuoufgrCevxqVXTQzfZKO4hJaI1HCq+KKrLbV8=,tag:99zsxlo+6afFCRZrtX1CGw==,type:str]
    HOMEPAGE_VAR_RACNHER_url: ENC[AES256_GCM,data:m0Rxgg==,iv:5MpjCJvb0HO5ba3wbYNIEFQIu2iZOPVjBKazIcwCWhQ=,tag:9Ef2lfc6ZTwiZRbud8g4oQ==,type:str]
    HOMEPAGE_VAR_SCRYPTED_url: ENC[AES256_GCM,data:kmBkTA==,iv:dzkBjJN6NpI4gVgR6wJl4TOoFFD7+r8N/pU9hlNhAQo=,tag:7tZaZrV3NAO8ZtHnakgy/g==,type:str]
    HOMEPAGE_VAR_SHLINK_url: ENC[AES256_GCM,data:Wff/ag==,iv:HPJD86zKyhC7yw1SZ7rxMxzrP13I27ygtvrzJnQ0yug=,tag:p3sv7P48Zqdc3l5EU9ZFJA==,type:str]
    HOMEPAGE_VAR_TAUTULLI_API_key: ENC[AES256_GCM,data:SNiPnA==,iv:t4Qtnki6byWXzQWAW3YXoh96iSHt+h1nlnznICLqUIA=,tag:b1YjOC+1FEYEft9YPD3rkw==,type:str]
    HOMEPAGE_VAR_TAUTULLI_url: ENC[AES256_GCM,data:c816/w==,iv:J89LCXkrLYAn47tRME4ZwkbJoszfeLR5G+qry+YyoEQ=,tag:NLv/2frL74I2W/87g+Fs5Q==,type:str]
    HOMEPAGE_VAR_TRUENAS_API_key: ENC[AES256_GCM,data:lL4neQ==,iv:X3FKnSFzzVWe04BCEwW0Du3lPK/Nqh1cXwip/C32zVQ=,tag:4hi4wl05EoQ2F7mLu89z6w==,type:str]
    HOMEPAGE_VAR_TRUENAS_url: ENC[AES256_GCM,data:wFxDW18rDg4MPRvwpSnu391Kqyjr7lryNRz6+FNtLQvyAjWD3eEtRm2nWiM=,iv:r0bAQH+KZ2FFtcGUBUne8C2CbkOK/QpM7TwANOohmDc=,tag:JYMWefrN9sNvTbiW2y+5tA==,type:str]
    HOMEPAGE_VAR_UNIFI_NETWORK_password: ENC[AES256_GCM,data:rfzNyA==,iv:giTBOyNHWjTDc0cY08HYrpSc2QGBhOw4RKiNBFBqJrc=,tag:qBMlxa5ai/5SnhIUQnfcYw==,type:str]
    HOMEPAGE_VAR_UNIFI_NETWORK_url: ENC[AES256_GCM,data:TRrc05RRNWqCXqOvaew5wCPcBErkH3yKGaEKf2IrD/DZBlKQ+DNagaGcuUiGg3sM,iv:V784Q258MUo22ujxQCPhxlcgpT+u0h6x+IhFDzkeKFo=,tag:9Dwe+k71sce2a2iRZjw3jQ==,type:str]
    HOMEPAGE_VAR_UNIFI_NETWORK_username: ENC[AES256_GCM,data:1BTZMQ==,iv:XqbBD2wBh/2atKqe5tsYYK1bx6WE1DWvrW/bmlIvS+8=,tag:yBmRH2ivSxCx78219vA1tQ==,type:str]
    HOMEPAGE_VAR_UNIFI_PROTECT_url: ENC[AES256_GCM,data:JK7m9Q==,iv:hywB43szal7Iy4HNI+hajAH3p1kLLc8f3DmdYQtAd7w=,tag:l8AXOU5P8EidNHbrKl9fMA==,type:str]
    HOMEPAGE_VAR_UPS_1_url: ENC[AES256_GCM,data:ZgQM1Q==,iv:FQYObqxBUUuZHKDaAzlg7x4rahzWaZpp/J7keVrLz+U=,tag:jWIQEyLFCOp6TFjJ3lPIww==,type:str]
    HOMEPAGE_VAR_UPS_2_url: ENC[AES256_GCM,data:8VpoGw==,iv:mpeW6cUL15CNbB+tRn/A233KGA8NzsxvHNw11Ic9zpY=,tag:AthkWNpz6Zc5Z6blJclIEw==,type:str]
    HOMEPAGE_VAR_UPTIME_KUMA_url: ENC[AES256_GCM,data:REmHVw==,iv:2FxEUoN6wIgseN4Bsmh1Hyv0X2KWPlpMkWDBM+A1fjs=,tag:nTOuVI8CgwChdjYLzyeXfg==,type:str]
    HOMEPAGE_VAR_UPTIME_ROBOT_API_key: ENC[AES256_GCM,data:4O3aaw==,iv:qmvUzMSbSOIZJh+2Ku3RFCMyb3ZSzxkOhyJmKp9C8mk=,tag:Us4TGEg47teTiZ46wJeR7g==,type:str]
kind: Secret
metadata:
    name: homepage-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTmdGSHVub2dsa1JMb0F2
            TEZMaVlSa2ljTWdzalFVYWQ1alR6d1dLaVZnCjIyT3NzZzg1QWRLU2xlYkdZUTAv
            TUZnd1g3UCt6YktZWnRRcWJ0dUcyaTAKLS0tIE1TeU12MjRJWjFuYUhweGEyeHdN
            Z3JOT2RzT0hOdTNEYStrd21kUDBmK2MKoLSitLQEoBW9JJtNnT0SBanDPaNdzhpe
            FOgI7GQRxD8ZDyKRc0u2Xor3tV4a5/PuiqZEJReiiXk6fOqakj7xog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T18:44:18Z"
    mac: ENC[AES256_GCM,data:LzqaFY5fOQjoO+2mkfztl0a01NwFkMcKNjyzFMVtXZQgp41/nnaVpIO6xZxbmU3zPbe1Vw3miDpXPGb9vlahD+fPlsl4HYKwjhoLvB6iOPNSyohUCK7gUHBWToCbM1zLiYY7uoRXMuA2aqKKdKLZ2wbG+0RJ6kMxRaeeHyuWhUg=,iv:lsct/jr4dk+3eBvVNo2Zq7m3IHEsEy6t9R+JQF287bo=,tag:KKmWcn3ECUIPf62NAci7AQ==,type:str]
    pgp: []
    encrypted_regex: ^(data||stringData)$
    version: 3.8.1
