apiVersion: v1
data:
  HOMEPAGE_VAR_BROADLINK_CONTROL_url: ENC[AES256_GCM,data:1rmG7Q==,iv:HFRO13+LmRU2xCmI54w62RDbyXCBfOpB3WQrRxSlDC4=,tag:O14Q3YehAgB5FKMsWz9Eig==,type:str]
  HOMEPAGE_VAR_HDHOMERUN_url: ENC[AES256_GCM,data:JyW/xA==,iv:w0EcIdy0qzOMYnKMu3gAAnzdmMdWUBp01oG+r9ubCe0=,tag:D37e14N0f1IMPHt0nwXW/g==,type:str]
  HOMEPAGE_VAR_HOME_ASSISTANT_API_key: ENC[AES256_GCM,data:KlrEbg==,iv:m3rKpbEXxZ6S3bLpEkNeQ410b95TTpV100bGKoCw03o=,tag:z7ErUGa1i8vWnqnOqVnkxg==,type:str]
  HOMEPAGE_VAR_HOME_ASSISTANT_url: ENC[AES256_GCM,data:oKJ8rw==,iv:JqqOQKT9YjlgvmYsmhc4uyj+6LAqHIEIxDjSxopiQAU=,tag:KLc68/40+WITss3JUFu3YQ==,type:str]
  HOMEPAGE_VAR_IPMI_1_url: ENC[AES256_GCM,data:sZr+uw==,iv:dvr9bmJbxh4Wi8YQapzhjcB5Pxvf15ZjJ5uFqvaJ8z8=,tag:Do4e7OZNqi+zCzquv8lYUw==,type:str]
  HOMEPAGE_VAR_IPMI_2_url: ENC[AES256_GCM,data:rdSMEg==,iv:ledRPTXYJepUj3y357AELSFaKerZ+AlG5Do03AeyKx8=,tag:YowMwKHGg5xwRXpi/eaxOA==,type:str]
  HOMEPAGE_VAR_LONGHORN_url: ENC[AES256_GCM,data:QpOuZA==,iv:ONHhe8vRxYP7sGoTu7sbuPb6WdVMg+hqk/nB+NDsgV0=,tag:VkDlXp5Akowp9Yq5OTxslA==,type:str]
  HOMEPAGE_VAR_MINIO_url: ENC[AES256_GCM,data:pDHOWw==,iv:hFo0/lqKN9A5oUJwRCTAC2sDD4eveOzxYXDmx73Veck=,tag:mJSiVFKQbBLkwn1EIjpccQ==,type:str]
  HOMEPAGE_VAR_NETBOOT_url: ENC[AES256_GCM,data:DNAMuA==,iv:ADOVnDj7GA7R07P/BwXsJst9u2n4h4yrRVaXIJdcWmE=,tag:AHnBaRsjsCTOEd5yh85DOA==,type:str]
  HOMEPAGE_VAR_PIHOLE_API_KEY_1: ENC[AES256_GCM,data:01nTHg==,iv:muEk0N97RbMwYe+hhU0TH1CTLKa5e82GD3um+1t6FT4=,tag:D4e5drFDnffHWu/Euzu7nQ==,type:str]
  HOMEPAGE_VAR_PIHOLE_API_KEY_2: ENC[AES256_GCM,data:mmU1+Q==,iv:ipJtQ4YZggxgrTtGah0PNxlvbFCjRPNV+Py1eZh0zDc=,tag:IrgY19wXgMQf2luq0f7gMQ==,type:str]
  HOMEPAGE_VAR_PIHOLE_API_KEY_3: ENC[AES256_GCM,data:inkiig==,iv:CmAUgExtZ3kdTt3B7pOQUpTH0S4+6ZZvUjLo6p9m7hY=,tag:ULEBhXt0ZOKIjICP6KMl4Q==,type:str]
  HOMEPAGE_VAR_PIHOLE_URL_1: ENC[AES256_GCM,data:jPVMjIFhi5zfzpRrwHVBoAQSR9EPbLEyMCCKmrg88W04AvNaqKwCAh8gX9cSRbQJpvGAHQ==,iv:mb3DI4WTMVmh9XamwQLZuGM5CL8eeAX4IehBR6EkKmQ=,tag:j5Ov4Wt49o4lvp66SwLbew==,type:str]
  HOMEPAGE_VAR_PIHOLE_URL_2: ENC[AES256_GCM,data:gAnC9g==,iv:sSmWD1Nb2ru47hAakYAGwpj21bjNWmUTR59OZRx7oQA=,tag:cH+Rm//DBvfNlhRAl8PirQ==,type:str]
  HOMEPAGE_VAR_PIHOLE_URL_3: ENC[AES256_GCM,data:PcUanw==,iv:eBpsE/Yo55gYqPJK7nkxzCNRAN9aXl5Tw5FhDWAQKNo=,tag:L68wYQ7EmgGlZxM/fhsnTg==,type:str]
  HOMEPAGE_VAR_PIKVM_url: ENC[AES256_GCM,data:byDFWg==,iv:qfWGH5ezSaDNT8q02jH2TNFEzV1YwYsQfrW3YmYZBiQ=,tag:KF+MZD8GYlXsQbCsJ2U9Mg==,type:str]
  HOMEPAGE_VAR_PLEX_API_TOKEN: ENC[AES256_GCM,data:NXyA2A==,iv:T37TnEMGKFzEA1NkVw9EXCeDOKZVLY7gIiXMlpWHzLE=,tag:WDkvXphT7C1vdrL0aBVg1w==,type:str]
  HOMEPAGE_VAR_PLEX_url: ENC[AES256_GCM,data:Zao9FQ==,iv:epaKvmwRaTRxymHjEWuTk3Q0Jf1rkN00igdIp4R5AFw=,tag:9IpngQlNu6VAqfazaY8/5w==,type:str]
  HOMEPAGE_VAR_PORTAINER_API_key: ENC[AES256_GCM,data:LuYdBg==,iv:4MCya1pW6aZIYuhEVp9k7wI53pP2e5T6zDB3PGpjP+U=,tag:sMaaRutwu7WI8E+a24rrQw==,type:str]
  HOMEPAGE_VAR_PORTAINER_url: ENC[AES256_GCM,data:/i+DFA==,iv:yiI06bExrs+6+skzdDJS+Evqp5gAtetKef9mEa9vk/Y=,tag:kr5Fv2t2Yg/wGGMWFiYfLQ==,type:str]
  HOMEPAGE_VAR_PROXMOX_API_key: ENC[AES256_GCM,data:YBKJe1G+A/VRy3baINFJv7rTl52ymGFelYv65xud2sQw8njavuUD55dlUpA38TQg,iv:O9tbgOdvMDest9O2WRajmU2JDZ3tSuQjsjOeh9Cm3sM=,tag:ixJCEUtY5BYyNVCRUNJyJg==,type:str]
  HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:5ps5TWWLR0G3qawd1mdnfoesLZn+n7xSlIzwLw==,iv:ZUP+jxB7rxZ4QvuB1bvXuVuWCCk1+p3aqTtrHN9rrjc=,tag:c1/7q/6uz15wtZe/+HadMg==,type:str]
  HOMEPAGE_VAR_PROXMOX1_URL: ENC[AES256_GCM,data:6Ze7KL1ASW6XfAj44Z65D0TFSJ6/awwRb4YRz71sKDheSFER3jFibkWKfSf7Vf2mnRqlqA==,iv:9zEKmKdOiFdDRSJ7TuXsZ8Iz4sPpZkb4nt+DXcuRlzM=,tag:wM1GZmuhKsTvOCJBQ1mhYw==,type:str]
  HOMEPAGE_VAR_PROXMOX2_URL: ENC[AES256_GCM,data:eHpI16ZRzWey4RWjUoEL1gfgVluCrED+jL2GC7JviIuYZqsnnRmKQTw+wMuDU7QGh2FOpA==,iv:AyEuz1SHPSQsYpIG5q3KzC1Ey9h/atZAk+vjtpgwyh8=,tag:Dvp6wvSDPvcy/WBevv956g==,type:str]
  HOMEPAGE_VAR_PROXMOX3_URL: ENC[AES256_GCM,data:Ar0EbCrseurYRr5oke0uMYz7Fv/EaGDDvkhIsJ6Qkyy/hsIie+Y+CnNZ0J4eiQbkVVphvg==,iv:6QWAwEjJrhrc9c+3kvL/fIOQvzxwCg7i7SqgBClPfjQ=,tag:C6gESCwVVeHdsdwC2IJS8w==,type:str]
  HOMEPAGE_VAR_RACNHER_url: ENC[AES256_GCM,data:msADVA==,iv:EQvQhaFryQK7/PBnf36jjE9+WXHoMC7pds68aYLC93Q=,tag:xCxLimrdKaSyXAkWlM+RpA==,type:str]
  HOMEPAGE_VAR_SCRYPTED_url: ENC[AES256_GCM,data:/IkLXg==,iv:J2NcvwiWpi5QZUU3K7dSfeHg+g7+0F8vv/dj28pfSF4=,tag:x6xWKD3xgAhVFj0FtxKQsQ==,type:str]
  HOMEPAGE_VAR_SHLINK_url: ENC[AES256_GCM,data:skqUug==,iv:/OTrv0SUjQ9Q8in50wV+Df3SHWAabTUti8zznR34aRo=,tag:dXvzWJ10+g2l7oH5O1hqnw==,type:str]
  HOMEPAGE_VAR_TAUTULLI_API_key: ENC[AES256_GCM,data:+Cs71w==,iv:GAw0mN9xAQRA8XajCARBIyYqPKUEiI04RSQHIme8Wn0=,tag:EDo0fjbmsrKn6OrIDCTWgg==,type:str]
  HOMEPAGE_VAR_TAUTULLI_url: ENC[AES256_GCM,data:zE9Ehw==,iv:UyszXqfm0FPANrYMJj2KJYIzO28QJdkGU7EhjEZvmS8=,tag:KUaFSivV/3/5bj9KjSvDRg==,type:str]
  HOMEPAGE_VAR_TRUENAS_API_key: ENC[AES256_GCM,data:mr5spg==,iv:/rsIQB7QSMaQY41A7jm0bx6RLEgL5ohASlNRl6wsdHU=,tag:MDpDZst12DklPh/xjopPVA==,type:str]
  HOMEPAGE_VAR_TRUENAS_url: ENC[AES256_GCM,data:IhbtmRQRH/snIC/1aXd7cxiiwbRa+39xWYxb3+4/gkYkuzQDKLv0nTM0wgo=,iv:f/AwE/pM3sXSNK/2Uqb1LCaphVtZJyu/uzqL36gDL/8=,tag:nd9NHWaed0iygDlHUQucgA==,type:str]
  HOMEPAGE_VAR_UNIFI_NETWORK_password: ENC[AES256_GCM,data:QGqHkg==,iv:6jwS4PwMJYExSxjn/0r+aIR5Ttzymbmll/YkmABW26c=,tag:gsdN+lSkL74ostbvNL7rKQ==,type:str]
  HOMEPAGE_VAR_UNIFI_NETWORK_url: ENC[AES256_GCM,data:ty6N3j+M0YLVVYivjLRc+683B/uziNfIrU2GvZ2RTTF2GbRVSZ6JzBl0ovWcNQ9J,iv:ziBiVUmp0fQ3+8dub5cfkQI8dRj1Y230YeBUkWbvhhc=,tag:ZXCjjzyhhlDz62ZgYpgdaA==,type:str]
  HOMEPAGE_VAR_UNIFI_NETWORK_username: ENC[AES256_GCM,data:dFC3zg==,iv:4uJ+bHQJBJ4jiOTpQMkSwvC5u5GWsoorwaN97TJVUZQ=,tag:BDg3qYAl/nx7hEoXQYoZTw==,type:str]
  HOMEPAGE_VAR_UNIFI_PROTECT_url: ENC[AES256_GCM,data:z2AzSw==,iv:dnmAdHV8+7tZuHlJhRa2XFTS0M7HKBU2IMHibK0JDEU=,tag:LsU1zPA67GDnaZ9f+D9HaA==,type:str]
  HOMEPAGE_VAR_UPS_1_url: ENC[AES256_GCM,data:clsQzQ==,iv:+x3+K9zFcayQZJuBVpzL/LslLzAmJRbWwpRgjN2enHA=,tag:nxtll17nt/LW2yDe+pfleQ==,type:str]
  HOMEPAGE_VAR_UPS_2_url: ENC[AES256_GCM,data:ciEUXg==,iv:chPz3REY4fsMWeiNxFrzo+bd4qpQv8RZkIQbj84HPpU=,tag:5yzcPLGKghCjVug6f+WbQA==,type:str]
  HOMEPAGE_VAR_UPTIME_KUMA_url: ENC[AES256_GCM,data:GrCNNg==,iv:y/t5uZq4sfFHr+gSKdBFSzit2N00eDAOC5KPje4ii/k=,tag:nhNsyJZH9+AyWaREs/VQwg==,type:str]
  HOMEPAGE_VAR_UPTIME_ROBOT_API_key: ENC[AES256_GCM,data:/8QARA==,iv:t51dVI618AAixyQtBdnKmXWAHhrJGPj77T3vfvD+KYQ=,tag:iE2BUX0bcFKj+UtaBxLrGg==,type:str]
kind: Secret
metadata:
  name: homepage-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOENNTTNud0NjK3pFcXFQ
        WlVGVlphSlVZM0p0MGZxVEs3UXV5eS9IcW13CjgxNmR2NG9ySzFlSkwwdCtmN2Fz
        WllFa3FBQmJSeG1ZdFJaK3N6QUNYdVUKLS0tIEt3OWVsSlh2SDVFQ254b0ZnZWFY
        bnBlaTNadXNNK3dxV1ROcERVeHVheXMK7KG2ADr0m1whApsh1Pnu8N528Vpw3s85
        a7fAzl5UaPhhvDQOwuIu5fZsrj2rJeniVAwPXZd19r8wS/sDYvhgqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-04T15:22:30Z"
  mac: ENC[AES256_GCM,data:HrB3y9dkRADCbhyeSMbjTxAk2HgiFqR/ZQWJlj7MEtOLtpzWYDvjKdWia9LkNpxXAfo6AvkVoCemNhqos4zQDO8K+ThzpegLP7cPv73hicnqVdzjX65RHsND1Z9X+gG0yee0XXSYDqY42XWOJeJSj4xm/kqwToEaIEjleM4JsAw=,iv:Lj36rmMB6syxIdZnrsFdwHSD/bYWFpsOjZUWReImrCM=,tag:TrjZgPR6Bvz2DKZjEmLOkA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|ip)$
  mac_only_encrypted: true
  version: 3.9.0
