---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage-secrets.sops.yaml
  - misc.yaml
  - cm.yaml
  - deployment.yaml
  - svc.yaml
  - ingress-route.yaml
