---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-traefik-app
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium-app
  path: ./kubernetes/production/apps/traefik/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-traefik-dashboard
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-traefik-app
  path: ./kubernetes/production/apps/traefik/traefik/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
