---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app influxdb
spec:
  interval: 30m
  timeout: 30m
  chart:
    spec:
      chart: influxdb
      version: 7.1.20
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 4
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 4
  uninstall:
    keepHistory: false
  values:
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 50Gi
      ## Configure resource requests and limits
    influxdb:
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory: 8Gi
          cpu: 5000m
    metrics:
      enabled: true
    auth:
      existingSecret: influxdb-secrets
