---
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      telegram_api_url: "https://api.telegram.org"
    route:
      group_by: ["alertname", "job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - receiver: "telegram"
          match:
            alertname: Watchdog
        - receiver: "telegram"
          match:
            alertname: InfoInhibitor
    inhibit_rules:
      - source_match:
          severity: critical
        target_match:
          severity: warning
        equal: ["alertname", "namespace"]
    receivers:
      - name: "null"
      - name: "telegram"
        telegram_configs:
          - bot_token: ${TELEGRAM_BOT_TOKEN}
            chat_id: ${TELEGRAM_CHAT_ID}
            parse_mode: ''
  ingress:
    enabled: false
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          resources:
            requests:
              storage: 1Gi