---
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname", "job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - receiver: "null"
          match:
            alertname: Watchdog
        - receiver: "null"
          match:
            alertname: InfoInhibitor
    inhibit_rules:
      - source_match:
          severity: critical
        target_match:
          severity: warning
        equal: ["alertname", "namespace"]
    receivers:
      - name: "null"
    ingress:
      enabled: false
    alertmanagerSpec:
      useExistingSecret: true
      configSecret: alertmanager-secret
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            resources:
              requests:
                storage: 1Gi