apiVersion: v1
data:
  SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:4fVdovGFVND2vImT+OP5WApSS4C8M0Gsw9JViQ==,iv:8izheYoed8uckfx5v21U64ngbu09mvt9yttD7AZN64A=,tag:hul0RfvmW3eGgO7Hq2WHjA==,type:str]
  SECRET_CLUSTER_LOCAL_DOMAIN: ENC[AES256_GCM,data:voejnItcnxRMPfL5Bcy+suIWM01Dk3xAtl6s4g==,iv:7PrN4Ee9+Dd5OjmTNzh7057CaYCm36OkiNffDeRs73g=,tag:6CEN6gfNJNbcRk/VYScq0Q==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:txtdzSOLSSUpB4ZiNJO5eyVJy5I=,iv:omYkFRHLq9FdGXx+aEWqb8OueqsmyF6NsKCNgv3tCpc=,tag:15QWcEAKTTdkEg90lUjEFg==,type:str]
  EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:PUY+wLwnrl8x0QLH93yrFOY2hx0=,iv:TwitNrVlES6gGx7wCdNDGZ/squ+jbzVWg7q05Fc0d8Q=,tag:esIqN3zCf8K8xMLykTYRSw==,type:str]
  EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:tHlyWO2gIpA=,iv:gaC+DtWUKCPXCI+IzfD9e3HXHEiKv5cyPBQlPeemYwc=,tag:OlSiNILWFmwRLTBTzCNimQ==,type:str]
  UNIFI_HOST: ENC[AES256_GCM,data:iw3TuVzF7o9xsNhKuD1Z9xkgAyzTwIC/6ncMlA==,iv:L0Ni/aC+djOrnTqMl9zjJChT1MiE9pG+6Hm5vDEwaeU=,tag:HX2kl0Ha2G05ERh2TROqMQ==,type:str]
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhU3JaN0xPQmQ2QXVSS1ox
        UjVhdGtvaHhnK2UrT3UvY1AwTnJRQXQrQkNJCjQ5Z1RzM1ZMQm4zS1JUT2w3blJR
        YUhRQXRhRjFVK3RKeklyYndSQzhJUWsKLS0tIDJtSEpMV2NjZVdhMThPQ0N2YTNq
        OERDSWhuWldtSU9NcEc4UUpaQ2ZYODgKDoed54nbcuqZHJWiT24L++wBWX1zG5nH
        sMwHTFG91jBs1quP4EhBjd1Ac3sRm7TX2nhY2O2oTpATjIX9Dxh1lA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-05T17:03:17Z"
  mac: ENC[AES256_GCM,data:8xOrE+8+8ZFihF5vfcJVce/JKr6Z+1mAC6PQlRv0Gy6IFK1zH/XPAqUqF2ntlvWSM8hbY5oUkT1MRY/J5eZVFnY38KqB72guaXLvyPygm4C8GMy7y1dYZtZVS0chxGKYroltA4E4O6sbs3bfzw9N+lgYQCWdya67/WgpaRtN5a8=,iv:mZp2K/nLN3hy9y5sKQbndpwru7OMskwc732VX8xGTwU=,tag:TXrWZyWewSmNRe6d/Hfmaw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|ip)$
  mac_only_encrypted: true
  version: 3.9.0
