apiVersion: v1
data:
  SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mDM/jBjFKSxGnEO7+xmpwyCPVlnEcHalByqNFQ==,iv:I0UjmdJtiV1uFtGHPi18/ngE98ReVvQ/CWPmoPhXWow=,tag:Df/4Gj+s/3qVPByHfsfNOA==,type:str]
  SECRET_CLUSTER_LOCAL_DOMAIN: ENC[AES256_GCM,data:lPVtg1FMXLffhxbPzcBvCKUHQeJiOpVCy3Gkdw==,iv:rVRmZA+rrnpCsW0RA5zCcybWik5iyO83Jddn3tydXLo=,tag:r2Mg4f0XpGp8WjfVRr9etw==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:3/FLQBxz/B+pchdukijZx+6ereQ=,iv:ajSqpw47P55vzhc41dwtPGKAyhKLpifM+ek/MAFTr/4=,tag:NiubfRQlFMJyXaD+3pCMHg==,type:str]
  EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:wakOV8s5vhZc9K5AUlve4HB/JHE=,iv:J4mayZwAtwEppM4SzjjbWdhhAyLXyIarsYB5zfLpeT4=,tag:rBF1HPBo/FBAyc+i8WFiCA==,type:str]
  EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:kOzNPBk7ar4=,iv:qyB0kTBqAQOAKM9tZhKLaBCcSszDIttosWag+5pwUpc=,tag:YobYuY7Qn1Kj+/LYt8BD0g==,type:str]
  UNIFI_HOST: ENC[AES256_GCM,data:nhz5hNDKIzU1ZeVvDBvNg7n6lzSe01xvF7VeFA==,iv:RVwIXm/IYoGavaJGbYOs7P7eUYGyjxXg7t6COMYDgko=,tag:lvTkXfgj3srTPuVcviQ6lw==,type:str]
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcGl4ZDE5dmJYdjJuT2Zv
        UEVLWW5FbVk1dXdOMjgxbVFKWDdUR3pwY0hnCnVGazQyUlJlUkNKWFQ3c2dmdHEz
        SDJsSXF5MXJHU2QwZFhyVHNnd1pFNlEKLS0tIEgybk5vRUhmdjZoay8wZzhXSjcw
        Tm1SaHJHMUpTU01VWlMxUzRJYmg5bXMKiF9uwqz0l4zGtRQ5incyjpW4A1r3Iz5k
        mwSh2lhHOgfeeLZOLz2lBH7jXX/YlkchlpX9e/9txG35+vmxc9wdJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-06T16:37:57Z"
  mac: ENC[AES256_GCM,data:M7oVLqg3DZEOqK1c5Gcv633k0XoIGHOvoMRUJBT6v4Yq9nEpnAod3vZekLI6P+W/IkDTNP0o7MKSAwW6DVXwYOZfLxxbqhZrTM47En33T8pg+2gNk20CnZlDwwSz4sOfz1t2hRw3gWfnCZA3sYMuNgoC6LoJgajmchVMVMYwzsw=,iv:KTNkQn2cXBkK6S7JHXmD269Xi/vQnT04DdoCoODzAZ4=,tag:q7OuBRxsJ5m+bEh98nuDew==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|ip)$
  mac_only_encrypted: true
  version: 3.9.0
