---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app telegraf
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: telegraf
      version: 1.8.55
      sourceRef:
        kind: HelmRepository
        name: influxdb
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    envFromSecret: telegraf-secrets
    outputs:
    - influxdb:
        urls:
          - "http://influxdb.database.svc:8086"
        database: "smartmeter"