---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app telegraf
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: telegraf
      version: 1.8.61
      sourceRef:
        kind: HelmRepository
        name: influxdb
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      - name: INFLUXDB_TOKEN
        valueFrom:
          secretKeyRef:
            name: telegraf-secrets
            key: INFLUXDB_TOKEN
    service:
      ports:
        - name: http
          port: 8086
          targetPort: 8086
    config:
      outputs:
        - influxdb_v2:
            urls:
              - "http://influxdb.database.svc.cluster.local:8086"
            token: "${INFLUXDB_TOKEN}"
            bucket: "smartmeter"
            organization: "primary"
      inputs:
        - mqtt_consumer:
            servers:
              - "tcp://mqtt.default.svc.cluster.local:1883"
            topics:
              - "smartmeter"
            data_format: "json"
