---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-unifi
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    logLevel: debug
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.5.2@sha256:e1eef62e8d9f1966def6f2efc89ff42bcaba1060b0c2957d9cab57a11c900d5c
        env:
          - name: UNIFI_HOST
            value: ${UNIFI_HOST}
          - name: UNIFI_USER
            value: ${EXTERNAL_DNS_UNIFI_USER}
          - name: UNIFI_PASS
            value: ${EXTERNAL_DNS_UNIFI_PASS}
          - name: LOG_LEVEL
            value: "debug"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    rbac:
      additionalPermissions:
        - apiGroups: ["traefik.containo.us", "traefik.io"]
          resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["networking.k8s.io"]
          resources: ["ingresses"]
          verbs: ["get", "watch", "list"]
    extraArgs:
      - --ignore-ingress-tls-spec
      - --traefik-disable-legacy
      - --source=traefik-proxy
    policy: sync
    sources: ["service", "ingress", "crd"]
    txtOwnerId: main
    txtPrefix: k8s.main.
    domainFilters:
      - "frandberg.live"
      - ${SECRET_CLUSTER_LOCAL_DOMAIN}
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/auto: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
