---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: homeassistant-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-For: "true"
      X-Forwarded-Proto: "https"

