---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager-app
  namespace: flux-system
spec:
  path: ./kubernetes/production/apps/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager-cluster-issuer
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-cert-manager-app
  path: ./kubernetes/production/apps/cert-manager/cert-manager/cluster-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-cert-manager-cluster-issuer
  path: ./kubernetes/production/apps/cert-manager/cert-manager/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
