---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app telegraf
  labels:
    app.kubernetes.io/name: *app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *app
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.32.2
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
            requests:
              memory: "100Mi"
              cpu: "200m"
          volumeMounts:
            - name: telegraf-config-volume
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegraf-secrets
                  key: INFLUXDB_TOKEN
            - name: INFLUXDB_HOST
              valueFrom:
                secretKeyRef:
                  name: telegraf-secrets
                  key: INFLUXDB_HOST
            - name: INFLUXDB_BUCKET
              valueFrom:
                secretKeyRef:
                  name: telegraf-secrets
                  key: INFLUXDB_BUCKET
            - name: INFLUXDB_ORG
              valueFrom:
                secretKeyRef:
                  name: telegraf-secrets
                  key: INFLUXDB_ORG
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mqtt-secret
                  key: MQTT_USERNAME
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-secret
                  key: MQTT_PASSWORD
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
      serviceAccountName: default

