---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - telegraf.secret.sops.yaml
  - cm.yaml
  - deployment.yaml
