---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      nodeSelector:
        zigbeehw: apa
      containers:
        - image: koenkk/zigbee2mqtt:1.42.0
          name: zigbee2mqtt
          env:
            - name: "ZIGBEE2MQTT_DATA"
              value: "/data"
            - name: "ZIGBEE2MQTT_CONFIG_MQTT_SERVER"
              valueFrom:
                secretKeyRef:
                  name: zigbee-secrets
                  key: MQTT_SERVER
            - name: "ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC"
              value: "zigbee2mqtt"
            - name: "ZIGBEE2MQTT_CONFIG_PERMIT_JOIN"
              value: "true"
            - name: "ZIGBEE2MQTT_CONFIG_SERIAL_PORT"
              value: "/dev/ttyUSB0"
            - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY"
              value: "GENERATE"
            - name: "ZIGBEE2MQTT_CONFIG_NETWORK_KEY"
              value: "GENERATE"
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL
              value: "debug"
            - name: "TZ"
              value: "Europe/Stockholm"
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  name: zigbee-secrets
                  key: MQTT_USERNAME
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zigbee-secrets
                  key: MQTT_PASSWORD
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
            - name: usb
              mountPath: /dev/ttyUSB0
            - name: udev
              mountPath: /run/udev
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          securityContext:
            privileged: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
        - name: usb
          hostPath:
            path: /dev/ttyUSB0
            # type: CharDevice
        - name: udev
          hostPath:
            path: /run/udev
