# kubernetes/production/provision/proxmox-vm-config.yaml
apiVersion: v1
kind: Config
talos:
  schematic-id: ENC[AES256_GCM,data:RWkVi4GkhCfJ8i2LLh98/8KqOPKP18WiYJTrdEUSdv7we9VdEFx2qbQoGJ8FocOl73o8ktpALp+otnFqui0e7g==,iv:uPnQB27cYqz4r5/lhBlMN0hm8/1aQMkxDlGvDeUjpS8=,tag:do++2PJqZsgJXKn+qAXHrA==,type:str]
  vip: ENC[AES256_GCM,data:U6dDBm85692rCT61kw==,iv:dVyGMU5mAlccoYaO+rv6GIhPVcTBgOnKTlAxIfcVGEU=,tag:R4zYtfuK/9ubctb1k3dm2g==,type:str]
  controlplane-nodes: ENC[AES256_GCM,data:Klu5UheR0e1blCu2m62eCQTuWZaO/qTYLxVT/c87bUdNlrvPuuWD+ts=,iv:NAl7y3SUu+D+22e8uHmOOBe4EhW9bZXx9BCmjBiLDQg=,tag:t5AuZ1LlFH21XVEWKwRrhg==,type:str]
  worker-nodes: ENC[AES256_GCM,data:uTupzC3mw+dTC+ReZDvoiY5aLJayCaQ+hAqp0xLDAH7Vi1cqY3N3x40=,iv:88yu94/TOSw9qjei+fxaiCXH9E5diR5n8cxals4YSKI=,tag:LyT/Rz1WL/TJSbQRrnf7rw==,type:str]
  node: ENC[AES256_GCM,data:okG067tDcqV7p8g3qg==,iv:NggyWatOBnynkOMpZ4CCw1fYTVUhDuECPVoNV5ixfKc=,tag:TCcvWHIWdU/zSNx8n5Acxw==,type:str]
proxmox:
  talos:
    version: v1.7.6
  common_vm_config:
    cores: 4
    cpu: x86-64-v2-AES
    bios: seabios
    boot: order=scsi0;ide2
    agent: enabled=1,fstrim_cloned_disks=1
    scsihw: virtio-scsi-pci
    scsi0: local-lvm:32
    cdrom: local:iso/talos-*talos_version-amd64.iso
    bootdisk: scsi0
  vms:
    - vmid: ENC[AES256_GCM,data:hJ9D,iv:DxBNymHzM86jDnu9kxxsmEDnCZ69zYulRLrmmO3G28Q=,tag:NY1M7YUwrAepsbDaNrOAQw==,type:int]
      name: ENC[AES256_GCM,data:D/qXk8E=,iv:ejBngn0BU+oVfkXMLPQMIn5OMJS94UQyXn5rxjSBa6Y=,tag:KhiXwrDuIi3JxTMmE/4mCA==,type:str]
      vlanid: ENC[AES256_GCM,data:+VA=,iv:v5IGGglwREX4enDUwuKOJfHXfVEXmZ8fOgQgJ1ffIls=,tag:1Om3cxmrUs9fqu661zwOiw==,type:int]
      node: ENC[AES256_GCM,data:LfPpAOaO4MATQLBeXkpiazD0JafCJOFo,iv:BPh9yRN6F4AM6ZulspUqDM3RhWcL/Mm4RRnK5Pz7Q0w=,tag:8YYvl/xVWDLEMt/s6IDyew==,type:str]
      mac: ENC[AES256_GCM,data:Cvbbb11hizgLF2nQ7JjkZ8I=,iv:SHG/2v508S8o0K/IQmQl0n7g3PWQk/q50yiQ0M7Lpfo=,tag:5mwdbgHH98lAdiyTpnrpgg==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:AVL0Z+onQ4v3EkY7,iv:7G6E5g8y9RbEriZAhqoQXj1VqJuWUfynseZtoJSEI/M=,tag:ByqKB9hNGFziujL2b1RZ5Q==,type:str]
    - vmid: ENC[AES256_GCM,data:CDHa,iv:Wk+CXfx+snG7X5zW0dd7eMxzzBj21d3EGG20yu0JL0A=,tag:QxP2wd924xvOiZhbR2F44Q==,type:int]
      name: ENC[AES256_GCM,data:YC8ONiE=,iv:jXEFpAtML6CHAc29rZHfedxgURuSzETa4n/vZgpVr6o=,tag:BUQq7MEjNatA7i4fXYLX3g==,type:str]
      vlanid: ENC[AES256_GCM,data:rEM=,iv:wkoL3OtqS9Uc3qtbYKfM7hJldxXzJoaivzj7dX8t7lk=,tag:Q0hJPiBy79da15P/T9sXLQ==,type:int]
      node: ENC[AES256_GCM,data:p2fOxtvkRQVGREipAI8OUMLIO1Ao/4xd,iv:BMIiTyM2xryy+F6w89dTKlxieyFhJWp26ojPyY+ER5U=,tag:mAHynpfWFrimYh2qXszmMw==,type:str]
      mac: ENC[AES256_GCM,data:AosdwJ5/WIFKTVkVeGz6w/Q=,iv:uTLkQeaDtaDxtvknEX4BbJ6kkw2b6Pj/WYSrcmhNiD8=,tag:+3E3GXA8BeJbui2iXDgHiQ==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:4QOELNJbD3ZX9EA/,iv:AQxIonxXI2rOtRRHg1rJIgSmQIf8mD22UxY6oxJ98gg=,tag:xu/Ex38+IpPx1CK7CzXFyA==,type:str]
    - vmid: ENC[AES256_GCM,data:WFAa,iv:TRwRgTXDoGcAb+xaxp+T/XoCiped+eD8JGLEBKQ6ajo=,tag:cWl3EkZAPT+NPlGLpCq3ow==,type:int]
      name: ENC[AES256_GCM,data:3bVPsz4=,iv:yCMnUKCMiXFhv3dFgslDTntvDO5WUn+sdTzPEdcGReE=,tag:CTqOxxfOD/ZFIjTbna6k8A==,type:str]
      vlanid: ENC[AES256_GCM,data:fUw=,iv:vIGbsPZruyGLSy4tieaWUoLwsa0vBImuYGLnCxwxi/E=,tag:H0Og2MyIOTRyapKyFa/how==,type:int]
      node: ENC[AES256_GCM,data:hEvB0j/FOlujQWz7Z933TEL435yeesS1,iv:YSvic1nWUSrHuP75aakhndUnZSkZXoozCPOikja7UVI=,tag:4ZJ+k0dx9jebzXMJLjb9tQ==,type:str]
      mac: ENC[AES256_GCM,data:A8rNAjLVnNxqHvpyQZJnjmY=,iv:y1f3EJX4IKjoofjkE2qdzvRJre+FaDI4OxCUWMjjyGc=,tag:RNdehWfgvrj0TjzaPws7bQ==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:RBk2pPJ9ipThL8IT,iv:7erI4qGFO5Mp2vjVm8clgq+FRg1WxU4k6IyjXfY/2g4=,tag:f/RWRphyIn4NzYZOoJPuiA==,type:str]
    - vmid: ENC[AES256_GCM,data:vFCY,iv:ieUzq8mitr1q9o2Kx0rbnLqOsFEU2nJip66QbTMNJKg=,tag:HvLXbhT4zG6/AGmjRBO2Zw==,type:int]
      name: ENC[AES256_GCM,data:XxCVP0g=,iv:GxN+ijqtbZI3GpGbwu7hTSBMbuUQ1mn9CyigsB9wLb4=,tag:RD0DRhTMvSzbs6eYHDjZnw==,type:str]
      vlanid: ENC[AES256_GCM,data:oeM=,iv:p+iJZWgbGhXvY7renuU7GBhXTMXUb5ODnwD2E0pF/kw=,tag:7WFp6iW3paxe2+oOq3z9oA==,type:int]
      node: ENC[AES256_GCM,data:7PFGH6cp3YiNv0nsZCpcsgf4ozuYIYK2,iv:KuRb1/1sYDANic3UjQmUVo75DoMIdEyZoDpo/3wQN+w=,tag:GFcKmTG+WKkhb8qvdVQi9w==,type:str]
      mac: ENC[AES256_GCM,data:E6bhJpwCTx6J0DpCfFd6IKI=,iv:tnYS5k30yb6C9TPWGoJHokr1X8E/wbfPtGDeCo+CpJo=,tag:NxMTd5C8c930Vj4y8SjsHQ==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:aMrCyCEQIGvWK7JgJg==,iv:uFlfhPFpdXmjiK47t+pydq3Ee/3yXeWpUfOe+JjYY/s=,tag:Uj1GvqpchXutZa1oOrBHWw==,type:str]
    - vmid: ENC[AES256_GCM,data:gC68,iv:s6smZYSfIr4In6TikEvJ3uuTMglKZQ3C/+1919N+2gs=,tag:GJLGMXYNG4eX3TyM8HinEw==,type:int]
      name: ENC[AES256_GCM,data:GY0Q+wY=,iv:2E7NrWyZrLMu0BCDL1CKBP9rC+A5dPdd14LaxX3IuNw=,tag:Z0CNHTdDWoFrLoJHBOVJZA==,type:str]
      vlanid: ENC[AES256_GCM,data:lsU=,iv:g+p7U7NQT7sjbn19NNlRJ02/NoQFsMhqNNB+5s8O4+Y=,tag:IZZdhAcUr/f4Xkyq1/wRZw==,type:int]
      node: ENC[AES256_GCM,data:lTvyWHJLS33M7UvRAA5ML3E1kVl9zLCO,iv:iiMQ3boJuIopBFZ8dmZg2UffVwhOMYbhkuVVETCSzjI=,tag:MVn9N1rxu+bFcSqWuBdGqA==,type:str]
      mac: ENC[AES256_GCM,data:KlERCon/EAJIonXLxUhcNwA=,iv:5lUwLrQxyeR+P1IipCgCAAx0WG+lgWdRHIk2n6S53Jc=,tag:rxzIuPj7wUUY4ZHgTTBuoA==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:jsdyv3V4RCvbDDmUeA==,iv:X7hMKFcWFVpHkzkgQssAek7Vlt1SiTjNi8v5Ovk5fK0=,tag:xe9YtO2Zc2W2QQJdP68CuA==,type:str]
    - vmid: ENC[AES256_GCM,data:LgZ8,iv:6hF+BEwcT2YxQ0CXKFtQwmJdh3SOEuYqEtC7X7CHRmE=,tag:8WsKMDJnzGIkZnU9gJmuFA==,type:int]
      name: ENC[AES256_GCM,data:GlAFOOc=,iv:y1Zg91IveYAYxzYVvTeZenOjg546v/J2HOQOA90uGq8=,tag:vEwK87b5wTcfmICnkRxuqA==,type:str]
      vlanid: ENC[AES256_GCM,data:YYg=,iv:dPLDFFUXzYmTk6xdwcsy2XvXFkoRqvRe67LRzfQu57w=,tag:kP6j2l6n2wVRdvxG9myggA==,type:int]
      node: ENC[AES256_GCM,data:5t5VBqTxU+qJy7qoE7Gt1E0Pv3k7Cg1Q,iv:McJOlGGIpPHsdFZj9t1EiF6J8r7w6y6s8ATlpEsckRU=,tag:cEs6BStRRoSp6p1FfdiaDA==,type:str]
      mac: ENC[AES256_GCM,data:lFaY5iBlvVh6EJovGg1WE6c=,iv:5WpWvUl7lwcRfEA9bAOM/hN+e88vVPESW450sWCMY14=,tag:wI2Wwd4S5jNppth2HaXQ6A==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:CbW3Dlj2sq0JeWkJJg==,iv:tuu5NJXAjHEr9mUVV7kINVrTz9i6IBDJiUbKSccEcbo=,tag:YSBClkHhyPPKjxeUec+JEA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKU1FHWlkxdUFJK3h0aER2
        QStqV2Z5bkpsZ1hZdDBSQlIycG9GUG9zZjFBCjJsVmFQUTh3eWtDcFZJR1N6UUJz
        YkZlWTJoa3NFNmR6SHpjOHZWT1VrYTQKLS0tIERsa1Fjb0R1Vi9DTGlKZjRJemNY
        MHc3R0xRR21hbUV4SHZKd1JkNGtlWlEKkw41VEDHK5U2/y8wX+3c4ytOFTJ+0o3h
        CXR+UltuqYy3eqPDRtA9jqtASPdyTVNBRY4TxQYJEDDG0yEwQRuOew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-24T17:17:24Z"
  mac: ENC[AES256_GCM,data:nhUMDO2ZE+AZx4aJKocTuZKoSkGjhIuSmesjlQtQKxWqfVJUbdLXpCCj8TQcSoRPG7219d0zykl6K5iX1K48FFXvvxvMJz4x41vmq6eZETsMWOQum2MGpuralqop6DXnaf5MlMSi2XEm5DfdqZ5DNpsPqq684PWe88mjgnA0rl0=,iv:9EC7rWbzHmiNT1sa/JGWaCaq+xeHwZa5oEM2W5SKua8=,tag:m5u/EA2G848HkbkZFVF5XQ==,type:str]
  pgp: []
  encrypted_regex: ^(schematic-id|vip|controlplane-nodes|worker-nodes|node|vlanid|vmid|name|mac|storage|net0|password)$
  mac_only_encrypted: true
  version: 3.9.0
