# kubernetes/production/provision/proxmox-vm-config.yaml
apiVersion: v1
kind: Config
talos:
  schematic-id: ENC[AES256_GCM,data:R2cMNenBrzpbQZtGl/l1UV1G3/zWOdNFuS6xVkbXN4LDpdT2X+mrQ557jzMO4Fp/mmbTzbyAjTkIthg9q7BA4g==,iv:4bHKMXLt3lDa2AeQt7GoUE1SSeP34Xoz9ARsx9FVzuw=,tag:Tisy8ZUd0u7TuwW+PQ7Nsw==,type:str]
  vip: ENC[AES256_GCM,data:yEgfnrZr0ETqq+f+6w==,iv:DzOBJNyno4+n+L7fXZCRpaFASuAQlzbRc44wKkp5P0A=,tag:D/YGtiopaXR/UImN04kiRQ==,type:str]
  controlplane-nodes: ENC[AES256_GCM,data:B/Z30IfDtXXq9TWDDFl3ghFgYVYAysyv0UfCs0mGfCLfOWqR0rSxfME=,iv:p5pN95e5cEs1wMGtT6UyQ992O/o+GvtNIKAw0YTKTFY=,tag:DTI17GeJ8LungpqvHuG4rg==,type:str]
  worker-nodes: ENC[AES256_GCM,data:icfgctZZSDsMVsBfmcJPfA6AuDNM5DK9GOOsjMJsZxtoPZbvD48MVjo=,iv:Tya02z5wNwzRznGW6lQU+fIqOOjhleVwfwS+LCi02y4=,tag:O74r7FXiF6NnnbA2DP7DKA==,type:str]
  node: ENC[AES256_GCM,data:O0LIBwGi//zd9gf0Rg==,iv:pjy3c8ioxJaxrNKNGJigI7Wz6WBcblnEp+rVHAkVdNo=,tag:Sk/6Xmokk0vuxEJc9LJezw==,type:str]
proxmox:
  talos:
    version: v1.7.6
  common_vm_config:
    cores: 4
    cpu: x86-64-v2-AES
    bios: seabios
    boot: order=scsi0;ide2
    agent: enabled=1,fstrim_cloned_disks=1
    scsihw: virtio-scsi-pci
    scsi0: local-lvm:32
    cdrom: local:iso/talos-*talos_version-amd64.iso
    bootdisk: scsi0
  vms:
    - vmid: ENC[AES256_GCM,data:FiAe,iv:0l4QN31Ixe5Vn7HPtG8zFlytTPOhHTsIKqLDV3YNKjY=,tag:mWAeGBeJnvMepeqEchUPew==,type:int]
      name: ENC[AES256_GCM,data:Cnpfe44=,iv:RdH8ty/7cUT4Wenj98SHyo39mU6bMRI+7sq83cvr1zc=,tag:2Ud7VR46mXoQ8zGimOZnAg==,type:str]
      vlanid: ENC[AES256_GCM,data:VcA=,iv:H5XLzpu1lP+PMv5EbQJPfVlll5wqg7na9rlaBTpk780=,tag:AVStHG34dboc+QsWkoLwcA==,type:int]
      node: ENC[AES256_GCM,data:NQS4ILdApoG2dd63QDNBnAGijtisXTx8,iv:a/idXf0XiZmC7yebrZmuXsSqonW203bVeO6RYdoOrfc=,tag:sIQIUh+aHraVuVKKiG4axw==,type:str]
      mac: ENC[AES256_GCM,data:Sop5Ob/jrruNG7Hm3pTmBKQ=,iv:7s9cGmTFKpoOHSbdNNTkzmJKrgGkBDzJ/cLV5NUNrZQ=,tag:iVAmX3Q1iB40EiVeITsyQw==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:lRlziJxlKNWP4LMH,iv:k+u+58YvsC0Px9cg7I1Qc0Ndt0oLRhhPNm77fE1yNR4=,tag:4DVIR50uiLuQsC5OScfIEg==,type:str]
    - vmid: ENC[AES256_GCM,data:wRvw,iv:lRhwq0FzUMlVDLoVsCZVaqUIT/9EN11xu3le1NmHHe0=,tag:ytiuTzQY1//TxLjThXi1mw==,type:int]
      name: ENC[AES256_GCM,data:YtMik3k=,iv:0pBMlBhsyMEWVJW9X21IpCqDPC9mMsaxQx/SRktHC1A=,tag:BuJNFuYHWpNG1wWLMuQxQw==,type:str]
      vlanid: ENC[AES256_GCM,data:XCg=,iv:ZgCu6O/SHffFaJpGz5kRG22GlZIwYz7rfutZC2nNGGY=,tag:jmYbPQMBz3i+uMFBU5qX2g==,type:int]
      node: ENC[AES256_GCM,data:5P6XZsDT99A9G3Qra/TaOXGcdrS22ct1,iv:OZl8JMshReowUXVClHt38Y0eOiLvlrGIo30DjAwoAnM=,tag:FvuTCKRuubp+aKMEeBYXzA==,type:str]
      mac: ENC[AES256_GCM,data:N2uDNL8oAuKTUdi3+QwPTt8=,iv:gL6S/q9kiQLq/RZ8SK7DkQMkaHXd0BEiCYkHyA+mAwQ=,tag:Yt9eMufKHIW5bjLbS6eyRw==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:yIOsVY/lpu3K+/f6,iv:X8qaDdQNa0fkzLeedl1teh36Cye/9wXdxjY43/Dm1Xc=,tag:AWTZhSYnf0CfpHpvSgSoqQ==,type:str]
    - vmid: ENC[AES256_GCM,data:uGe7,iv:MX6nmvtzDp96tfwaW/sJjJE4OIa5mjFtDlNZ5tHiHjQ=,tag:GayLEufP+/sp6GlrtnW36Q==,type:int]
      name: ENC[AES256_GCM,data:7NLpHyI=,iv:Jn9m9seF7DZVFDVvyUiDlJGgnIlQi8YaHSMUIASNSc0=,tag:fhWTFm7mODYlC0KFrRucAg==,type:str]
      vlanid: ENC[AES256_GCM,data:frY=,iv:+xjQJhC53tKMDakeCoe6HrFItT7QVlXVvSPkRNYqFAM=,tag:bs8Cz5fXpJgsFqNuQC4DYQ==,type:int]
      node: ENC[AES256_GCM,data:2WYIc11tAzGiFyQLXNxYZvpC/CDdcd4+,iv:kmwTATjUdmSs/5BeRpLn2DN/s6JEAuWMwK65XSkM/3g=,tag:JfAR15R9fL8MYP/J6LHTPQ==,type:str]
      mac: ENC[AES256_GCM,data:q9Oz/RZY0hhWS5+CdeHgEI8=,iv:e/YF/P4e0vhYkLljnnluibl5eYXLBaAoiExpKlO77FA=,tag:jfdYOOGIt0wl6oxo/YnPxQ==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:9pKWbOfckikAin72,iv:z4hDn9lph4/4a11kKW0kN2n8jZglU4PaTfLEn3yRK84=,tag:kq7uHkKCE1b8xp0V8hbujw==,type:str]
    - vmid: ENC[AES256_GCM,data:CoCF,iv:CKlz19+ChmRRjTWD5EGaMjbsAx9oTo1KcLu1LamW/oE=,tag:htl+bPjhzWuaA1jF8zqg5g==,type:int]
      name: ENC[AES256_GCM,data:wDIOs8w=,iv:t38y8znOHkGFjc9atzFN44p893LrydwusHgtHNgW1Yo=,tag:hqoP5IC+7Flj3bhRdUJhng==,type:str]
      vlanid: ENC[AES256_GCM,data:qdQ=,iv:iiayJMuQ73Ir7eTRISyZuBf/6KVIuqzIPJUYdbvT7wA=,tag:/zZ3AeWXoJmop9GGXWwMWg==,type:int]
      node: ENC[AES256_GCM,data:hNHaEFBmKli7imByzz2dgoSSyMCTIP/m,iv:gnsTyLets6857IzEKCeHSFJkk2jGaAlttqqUR2bh3CM=,tag:3FJPW2QsoCKe1KDa34z42A==,type:str]
      mac: ENC[AES256_GCM,data:P2PS/HJQxC8OOurl5h6anRs=,iv:CidcCA7WuVeTmdhcuzYSap6pw7n7/1RrYEEXFjZaRlQ=,tag:QQHtozKp7/auVuL0PlczyA==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:+QYsa2F4lEjwyceZUQ==,iv:zg3FfZ/CiImc90bnjuCV3QxPubX/vkPb8WmVnHQPfW4=,tag:C6S9qpjpfPtnyieptjy2EQ==,type:str]
    - vmid: ENC[AES256_GCM,data:uEbz,iv:Vk9YeYPEj0RADnjvl6Eh57c2tiapfXqe2XM7hJx6kz4=,tag:WIzNXQk1YbLCJLXhtQ1Rzw==,type:int]
      name: ENC[AES256_GCM,data:Gird+MM=,iv:ovHQ9FMS62JgntLWhiPNn7iRsvgz+JPg+9Gbd9eMdFM=,tag:TmB/2+83N67Y41AYKhEJWA==,type:str]
      vlanid: ENC[AES256_GCM,data:qO8=,iv:ahHC77Oi1jC1ehHiEm0zvIpUYkzNnbhRvHlcY3jfu9U=,tag:GuYx+OiaNTTHMc2za3hx0Q==,type:int]
      node: ENC[AES256_GCM,data:zrsbx6TJXCAWrPF2DD0z8THQDPwyVoxH,iv:WXZjdaUrmOHwwXlJGCRYbdFRSAi/8iuw9+jW07G5CRI=,tag:dDyKEggI43mnjOlvrk7l+Q==,type:str]
      mac: ENC[AES256_GCM,data:pfPSqR2MT7OB0n2Jjh3faOc=,iv:v4IFyGtRDnC2L20xXkQ5oZHdmZY+bpERqTuJnnMcu3A=,tag:aILGVvfXKVjHjOugG8XUow==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:GVfYmyKmiAH06Ky72g==,iv:FGMO14fkrE6JQaJLc6kEc9MSYgSk6g5l4CR+OSCh8Ys=,tag:a6ScE+PX7llDwvvEG0q8tw==,type:str]
    - vmid: ENC[AES256_GCM,data:yFtt,iv:rS2ancDSyWqQXlnFd2QyLr/qq6va/Vrt/RFLkMR1l7Q=,tag:iyMu9IC+pcnadJdjpKLaGA==,type:int]
      name: ENC[AES256_GCM,data:NltHmjI=,iv:PBx3OcSoVGjMpIryR8cJFcLW5qwlrfRALSsrBhu395g=,tag:zpjj/3XXf3ZJJW9qMMvAxw==,type:str]
      vlanid: ENC[AES256_GCM,data:koE=,iv:0wo693+iD/9VrCbgDV6T7NO1cA1bP0oSQci6BVHFCKo=,tag:Zd3X8eg66bJ6NI317sTqag==,type:int]
      node: ENC[AES256_GCM,data:cwsG1XONl56yxdloXwbcBgyR5t9/pS/6,iv:U3X2pTDazIyEjCrI3PIPx5yo+xW3WElWzHOoT4ZKHLw=,tag:d+QKxn4Rq3bfDkArswlJOA==,type:str]
      mac: ENC[AES256_GCM,data:FQVwWxX8Snnb6tV5+5FLSlA=,iv:dyolN/MT9v7e1Ye5HSOpPOm+H1Gyvr9LMbw+L7tjG4c=,tag:ulDyfjod9p91g/LF/mtfXg==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:q+jbAw5hT2i46B23+A==,iv:y+cemt6Wk/A2ph5IHuSZ0x/ejmKJt6+M0Yd/VtewVp0=,tag:D/B/pLGLPGiKEuG2NBVsgw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWlU4am5LNmFscWhFMkxn
        eHZFbW9RYlYrVGlNNVp3SjFkUzFYbW5UeUY0ClZadUtxdytzVVFLK09DNHhleHdV
        WFBEaVRaUzN5cDlnTk9kZDFSUWo2Q0kKLS0tIExpdVhueFpiYXBzbHRoUnN4dksz
        a2ExZUdhbmNNNE9rV0tHKzkwK1JHWm8KfHNgEJrSAF/3ImBa2NGTRZhosV2oGq3A
        ytDUBhgJ21gN2VaTa0cZ9jIcs1r9X5ixVu1WA7YagLZq2HwquXckeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-05T09:11:42Z"
  mac: ENC[AES256_GCM,data:bv3YvVzs4SaFAONN2sm1+7Pa79vE7buwnZEpWp3kGvL7qwURzNbsYwfmeqoE7IR1k49sL/Z87rEOyeaETI6fz25vZFzhYmH4aQ+RddVm5RjsJss5RrUF6xA2aaZ3OIOguLkyq2EjbVeBrhA8Xmr6T3O702354ZslI7gGqyayHjA=,iv:46gM/fBM0gurSiWIFSjP/KQHX4TP6Emf3ZTUC9hh1Sw=,tag:9Ntspqo02bmmQSHhq+GSKQ==,type:str]
  pgp: []
  encrypted_regex: ^(schematic-id|vip|controlplane-nodes|worker-nodes|node|vlanid|vmid|name|mac|storage|net0|password)$
  mac_only_encrypted: true
  version: 3.9.0
