# kubernetes/production/provision/proxmox-vm-config.yaml
apiVersion: v1
kind: Config
talos:
  schematic-id: ENC[AES256_GCM,data:UxU9+tN5qiQUbmGc+DoNGF/m8fUjyHrJlN3hYNoy3A9gF3P9eQfx1pF0h76neAvXEDAVdzQsK3mGNLtL0oTYWQ==,iv:lpOi/obts1HMmcxOsSfY1scFtPuOSxbqES9DVuA6NI4=,tag:1A0cf0OihFcFkI05ZBWqEw==,type:str]
  vip: ENC[AES256_GCM,data:371RrLk747jOYLTzFA==,iv:U+gixa7QGrgUV//C6kUPz1NuHignKu2K/dsDJh4bEx4=,tag:aaLYdY/WZvjLHn0+63Vuvw==,type:str]
  controlplane-nodes: ENC[AES256_GCM,data:iN/6zTl8tCFAx2cBQvJfwY/hvbbIcDLtUpkNYgcNRUKbwG/drIffmII=,iv:xJNk2kTsQuU+oh2nRY+jyF1AHHqssjt4QpkjNEiN7zQ=,tag:6R/uvVfV/wS/uGe14UnCnA==,type:str]
  worker-nodes: ENC[AES256_GCM,data:Zm6CZ5jRKHKErXVXg9Z9yLQa0rhzjQ+HJ0bgkyhMbTuBTkZuxx4y0Ss=,iv:vaIXbGnPNDJ5JxJyEKBx3KlQzfOahVkJ9Ev/WnGvalM=,tag:g+Q79S+7oA2HE/K5N4Vi5g==,type:str]
  node: ENC[AES256_GCM,data:h6dNCMHqq0Q9uj4JAg==,iv:9Qw58EzYKu9KTmCwL49AbM3NHTib1HR8oj9WjHq3lSY=,tag:/Pb5N0W7DMk4rlRP1hElMw==,type:str]
  # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
  os_version: v1.8.2
  # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
  k8s_version: v1.31.1
proxmox:
  common_vm_config:
    cores: 4
    cpu: x86-64-v2-AES
    bios: seabios
    boot: order=scsi0;ide2
    agent: enabled=1,fstrim_cloned_disks=1
    scsihw: virtio-scsi-pci
    scsi0: local-lvm:32
    cdrom: local:iso/talos-*talos_version-amd64.iso
    bootdisk: scsi0
  vms:
    - vmid: ENC[AES256_GCM,data:4j+0,iv:z/uY5HNhOXEGEARMVyJSBw7C3/GLhaU/Ok2iyIvF6m8=,tag:swGVP9ECX3GLb2LcVvcPVA==,type:int]
      name: ENC[AES256_GCM,data:6sJvSAs=,iv:7FmJH5SceBUHYQpamxJS0ulZzWBfpccbZCdZYkA/6f4=,tag:u91nAbHdUTX8GQYW7uJPig==,type:str]
      vlanid: ENC[AES256_GCM,data:IXg=,iv:8YTdNJohRTSMFvtaaXMIsJrljaWXZPB9BV7SelToU7s=,tag:HcOwXt+IFm0bL1BtPeBqqQ==,type:int]
      node: ENC[AES256_GCM,data:qdhx+l6uAMKWWG2GJxwK7XpUTaFx28i6,iv:wCoI1BgFqB0hy7lnU9PZ4nc7ual4VVHl1SpwQbRrO/I=,tag:RcOKOA+6urIZKoUqy/Qrqw==,type:str]
      mac: ENC[AES256_GCM,data:8W2ckLwndHKUvfX776O0N3U=,iv:xvb/9aDe6scot7i3oNb8FuliG/6+0FFm/P47M9tQXOc=,tag:C7IhT+waM5v9ecXR5iPJrA==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:adAxXe0cMsyamGtI,iv:Zm3kCRyQMJQu1PgQt6hqD+mv0XJmMo6UZkgfErNi2Yk=,tag:bxkxCqWviC3rqNjLRPoweA==,type:str]
    - vmid: ENC[AES256_GCM,data:doEQ,iv:VvQrnTzY6pENB2Xt1P+AFUMyz7dranxuMOwaW/PfkoY=,tag:n1K9obP92uTtvcuc4paAgQ==,type:int]
      name: ENC[AES256_GCM,data:3oBgLW8=,iv:gB+C9SybeZ4KLp/8d2z9hT6o4oAj0oaBqpLFNufybTQ=,tag:Dsp8iDS7lLnxBoFNn8ad0w==,type:str]
      vlanid: ENC[AES256_GCM,data:T2A=,iv:Bc1pM63yt9sMOJ41J+OFQDw9LAz/QaDRieb+Vp2mJYo=,tag:clg8EobE3CeT9tIp3zTjOA==,type:int]
      node: ENC[AES256_GCM,data:HUHKu6br+mksSGImwpzp8RwQcJliMAc6,iv:9ejhHE5GCwAnCupStBNZcTgiC9Sizfg5sAbzMUdO8PY=,tag:wG33kBvJaMmb54pZqHzguA==,type:str]
      mac: ENC[AES256_GCM,data:YVXegaDvi/sk7IK81+YhEws=,iv:dZm2MmrartwOaFl8k1uN/6hqQa1UiTaz5vWrCiw7kAQ=,tag:GoGh9m+MKbfafdo0gyIjzQ==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:mezgsEmAYRqRiu0A,iv:OoBMgzv8w/fEdhfmUYCh+6y2s/hyw1oZgu8eB6l/mpY=,tag:mDllnPuM6X5KukP7I9EDvw==,type:str]
    - vmid: ENC[AES256_GCM,data:53NT,iv:Ew9GofVtlwZT2dMvdA5peVHcEVvCJtyDQmIvoybQtaM=,tag:M4LE0NkTvBnZ2582KlwIvw==,type:int]
      name: ENC[AES256_GCM,data:i8aTTr4=,iv:LJb+XHUzGQ9ixRMeljvhk9USc/RhUm2Zd0ijIGGFVbs=,tag:tf9XwxzXCW6ewb7nZbyTAg==,type:str]
      vlanid: ENC[AES256_GCM,data:poM=,iv:8Dzx4d1AmU/scpz0bMbcj7eqNJ4YaPnYIIwaKsDH35A=,tag:nvsP8ime32ewzR99FL/GxA==,type:int]
      node: ENC[AES256_GCM,data:kPgVw33gzt8NuZ4KUuEW1YT1C/xjD1xd,iv:i+Ac8ovwidb6r6wcQGap/FtUcfv1enMJKixP00xTWgQ=,tag:WeJ2LTpsm0P9szC/IarEdA==,type:str]
      mac: ENC[AES256_GCM,data:yROoVFEyLxJp4Ugic1nHABI=,iv:Si9ZDMJCs975JjNm8kzqtDDwRq4nVDHLE52b64fT/9k=,tag:cjr6d103rZ27t12ymNzB0w==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:BlfAigSo3qYDIfDi,iv:68XcVGMJkiK+SqWyEMOAWAPh4zG6ht/0YL0L5q3FiDI=,tag:CJWD/knuhYyD+LU630p8WA==,type:str]
    - vmid: ENC[AES256_GCM,data:VRym,iv:uxTWS0t2DAplca3wiyYxKgttNga6bbdZbAI5vsrAxDs=,tag:REbt9K/7MlUjpQGRMxo4jg==,type:int]
      name: ENC[AES256_GCM,data:PbMX1gQ=,iv:UWaAetod2F5nyt9nIeBxU+eJVHGMH+qGOFeWbvPEc2o=,tag:ZzkhNoMVoGr1pzcQx27b+g==,type:str]
      vlanid: ENC[AES256_GCM,data:yE0=,iv:ZYkvLoYhU69ruH//TxJLFrRK8HDERC2oqB3j0xzaCaE=,tag:/2ZTa93x2yI+OQVGRWxjew==,type:int]
      node: ENC[AES256_GCM,data:X+il11xTx2ARjZbPSmz3o0xLQQ8gxdGn,iv:BKuH9C3mziYNDXUMJ0NiDXKGrIlPSa2/FytVX+TCX88=,tag:JbQoS4NqlxgwozBBBg7aDA==,type:str]
      mac: ENC[AES256_GCM,data:2Urt4tGGVl33PUcIu1rAy9Y=,iv:Ky+LcDYh+c0aAjqe3YvLdSjzLWtdc8vGokVjulNzu7Y=,tag:jzAYQKjNHqtlBogV9xGYWA==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:B0sGQiIxDTLPDA7zFw==,iv:o+tvE30eZRliNzKh94K+eGtj6g4RetlGtzweqwcTjUg=,tag:SyYBwGQWTvZUlLbJ0IJbTA==,type:str]
    - vmid: ENC[AES256_GCM,data:+kRo,iv:LESuR6/rAiWUl/Tu3NklEpkxtRww4/q7lsW4trIT5fk=,tag:B/6VScAJk1UkJRC+JFRAGQ==,type:int]
      name: ENC[AES256_GCM,data:oCsTgqg=,iv:N5c1mUANMnwO0Ny115Y0oS6geE4fj8F5leDICOdqbmc=,tag:54OrSr9RtbNw9kG4cgZ/wA==,type:str]
      vlanid: ENC[AES256_GCM,data:3fc=,iv:4SYLc1LHSrTrxSe3kjJ6W+8VAb61kveqA+gGyOBw198=,tag:l3z16Y9gucbODRNnn81HsA==,type:int]
      node: ENC[AES256_GCM,data:tkZmIBF78ghMAc+xyI6eQX4n+WByIdha,iv:+SzgtLF/l2cVQtQfizEYcmA6X2jr1cgHoaaM0Wfwm+E=,tag:y7oAb/OuEATinxgBvssXAA==,type:str]
      mac: ENC[AES256_GCM,data:O1Lszrp1mrsvAO6WDsloJkg=,iv:B0JDNbe3V7+zmqn4yjdb+Zr4HhM401rgHOpaWy80eHo=,tag:qudMqjiVrc+WBIs6/U1IXg==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:2Flf8ITTXKO78ytjcw==,iv:vMzqHpI27pBvbqZ64xRAO/+DWtdy5pHdyyrOPv/MSK8=,tag:q285uWQFRK6iaDtDdetjSQ==,type:str]
    - vmid: ENC[AES256_GCM,data:AnVG,iv:pItUiURGiRwxU4U5ffA844/l0V4HXUsS7EVos/Fqx+M=,tag:O5/pvvTM7l6Lr7h4Waps2Q==,type:int]
      name: ENC[AES256_GCM,data:ie/+WFQ=,iv:L38JF3DqcyRcR0axEmoy+S7ViZcRxbUREjg5zfLpkN0=,tag:A/FdSydvUUrB6XjYnn74Gg==,type:str]
      vlanid: ENC[AES256_GCM,data:SnE=,iv:uEEXoiiMToB7cebnc7wC5OKoLcrLkSq6++LhFQU2XLk=,tag:4SeJqjjBNe+FjwnfglsG0Q==,type:int]
      node: ENC[AES256_GCM,data:nnTlRxCJm5udr70KeAk3II7hHCwIWbVd,iv:C8SwYMijMZU/4/ylNP+BeAqgxkqRDmq2z/MwDPYk3jI=,tag:ugIhJXaQ26yOXmL/AYKDTg==,type:str]
      mac: ENC[AES256_GCM,data:NqHf+nwiZbz3UaUsMAFTytg=,iv:KAnKwV6gkhkC8JClK7pnVlFwQcmTq3E7zbdashKv2DA=,tag:WqdbO+0vwEnc18CXYodgiQ==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:23YFYoVGDIFrlP/dWQ==,iv:MU3rd68UiTZVTxqrIbNaPs1Q63ng+y7kDzxFxrPxoHM=,tag:G/r0yUaLGmgxBkYKchSHHQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS29ibWJKNXBML2Y5SGov
        RlB5SmdjdWY5eHgyU3l0RnNjNUpKaE5sbkY0Cmh0QU9XNStYSVIwM3h4RWZlcWtM
        NSs3a1FYQXlUYkc3MzRHdGdIUW9uOW8KLS0tIFYyWjU0cTQ4MGVKMGlPMFdDaHNI
        THhVZ1RBeGVJYytRc2tJNEF4VUpuc00KIfmNy5ZnlIdRPAzKtUfcmRW1yIoAtHhR
        lwXwwdAnK2J7/quMxmuBIwpjpm0j7AKMHKxr6V7QFX2pFOdxgEagnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-03T08:38:50Z"
  mac: ENC[AES256_GCM,data:MrS3NSkom0bEumdX65qSGJEqkNfFIq+hA1mZho9sgJDNYTPY0S6vLJwYUglcVe7mTvUgZMMFkmd0gVKgu38NYW7H0bnar6P+ZyUXxKWbtnpVUcJpQ2CkZDltM4LnChHjo4Y4sQN4liYnHvfw1TC+mpxpTQxmB0XlNotfDajtiPI=,iv:oiMXytoozwPLUT4DkoIN7TZrwtDJHWwA77pYf95evFk=,tag:5cUUfhdG2aXHTj0sS5sgiA==,type:str]
  pgp: []
  encrypted_regex: ^(schematic-id|vip|controlplane-nodes|worker-nodes|node|vlanid|vmid|name|mac|storage|net0|password)$
  mac_only_encrypted: true
  version: 3.9.0
