# kubernetes/production/provision/proxmox-vm-config.yaml
apiVersion: v1
kind: Config
talos:
  schematic-id: ENC[AES256_GCM,data:wgAUqDSCXmR5SgsKqMejn9T3TF64hJLvJwdvvbrPzM+ta1FCBRnyfXK6eYunD3ZRG9rr8jYBRigNJFtS99vVtA==,iv:cCBXFCW80aZkazdtSI9qTdLBnSkyJhv/SYkyG4/VX6Q=,tag:Qn6xdRUt5DmETTzJ/igxWw==,type:str]
  vip: ENC[AES256_GCM,data:IZ6CqNu5BVv4QrTeMw==,iv:+jxtgiXeas2P49LXWUEvhg9af8aazEyFVCL1RTfZLPA=,tag:plxa98xgFNr49dOuZJbWZw==,type:str]
  controlplane-nodes: ENC[AES256_GCM,data:1KM6JpEZvFPGCatlOWTCF8jvdSWcfZ2KAFaQb6bGIqxJWQ0TmiIGs8c=,iv:vrwwiQgiYV23ErJm5Gp+1ZN0Myp7hXewKSja5II5CKg=,tag:e96GOnWTD4KimGHWQwoAEQ==,type:str]
  worker-nodes: ENC[AES256_GCM,data:KG51wkE/3yQEMfOLbOsEsq+smDWTCREAHJaLPw3s4MILEmUWq1C7ObQ=,iv:LIMpo8W1w1IfdIoyXKWNm1qkgu5C8WrxU9jjqYWkfpw=,tag:zsw8Vb5y2kwB2bifxiS3rQ==,type:str]
  node: ENC[AES256_GCM,data:8k0vyaRcETkaXFo2DA==,iv:2dE0MUieIK1lQQynwlgDOLm7JBasTz4UacGKz394V5s=,tag:67msCPGslmu3+bxaHTSxCw==,type:str]
proxmox:
  common_vm_config:
    cores: 4
    cpu: x86-64-v2-AES
    bios: seabios
    boot: order=scsi0;ide2
    agent: enabled=1,fstrim_cloned_disks=1
    scsihw: virtio-scsi-pci
    scsi0: local-lvm:32
    cdrom: local:iso/talos-*talos_version-amd64.iso
    bootdisk: scsi0
  vms:
    - vmid: ENC[AES256_GCM,data:5fsr,iv:WQfqwsEEPjd8wOJ9isc56Lc1vH1Nic+gPjwIF+YSO4o=,tag:r3fPKwvGjpKrcE03SRWUAA==,type:int]
      name: ENC[AES256_GCM,data:gNKnsc8=,iv:DTvhb0PNNkR6/63XQThPWE9AQKGygjiAeFoRgo2zLC8=,tag:SjNFbYLx3nBnTb1U7b76Eg==,type:str]
      vlanid: ENC[AES256_GCM,data:CvE=,iv:hM+swQjTwEBShomRHWpKNtgM1+wCbW5cAC94GCbGFqY=,tag:64EAYXp1+B5/z1BThBWhqg==,type:int]
      node: ENC[AES256_GCM,data:FaEg2Z+1aLTTrsDPHqOR8glb9eCBdkX5,iv:aL4uIl4OvYATpXk9MjZ/w4KLppwHepqi08/ilDx4G9c=,tag:K6R/JOI5Gmxb7StkL6+KkQ==,type:str]
      mac: ENC[AES256_GCM,data:23ekiKg4vAZIlS+7ctGHX/4=,iv:ZCT94LCyF8uSTpdBt9rr70gEPpe3pfT5FmdG/2jd9s8=,tag:ZX69GxDo4YNosHAc/BNixg==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:x1rp6ptKP0IJvGwf,iv:N+CotvYtmsxC55BRGnwz5OiEKNSg+oFoNyvzILYh+mI=,tag:8B3j0Hm9WB7sQoBWTkkX7g==,type:str]
    - vmid: ENC[AES256_GCM,data:AWEV,iv:oT5i7TeQrWdN2JZ7Hf7jrD1dsFdfvDSiNl759zjM3TY=,tag:W/3eNDrebZoeLTf4ip2mQw==,type:int]
      name: ENC[AES256_GCM,data:yhsPkFg=,iv:7OKjuKRRUVPHYe39uzLq8uYIKjlEHgoS+7HqIeSNDbk=,tag:dn/KuYOwdlQXT/YmXMfa7w==,type:str]
      vlanid: ENC[AES256_GCM,data:Uvw=,iv:owLovmXed3iqXGvRqiVxYEp4jgaQ/dqASOOTqkOtQ+o=,tag:K4dnaNkCsEkmh2hGfwX1cQ==,type:int]
      node: ENC[AES256_GCM,data:5fYtuuHDL0Tq5SuDU9NCWn7NqotmRnyU,iv:/oz4QhhWl65A2buFsEAViRdst6VeiEIZwmaz7E+uF34=,tag:rBO4pVsHbJf5XVkPbaB8vQ==,type:str]
      mac: ENC[AES256_GCM,data:euinwc7qz6qOHiG6CCLqkc4=,iv:VqlnzFfWLcXCAFnoJVkadnvXGwpCRoFqd4Y3pp7de5o=,tag:h6EldwFG66YBoGaqhJIwuw==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:NeJE2tZRd7lAzKg5,iv:JJv2XHq1nz6Yyb3drF+5iTEx/Uz38JOY7KfZ4MpLSNI=,tag:HLaL6yLIUN17Wl4HeDQ7Jg==,type:str]
    - vmid: ENC[AES256_GCM,data:riVR,iv:vUuOSU5OY+grYv0VL4ol5qdeEutZvE19VL3xh6T+ZXM=,tag:tWxp/i/4/XDomu7lOIOtCA==,type:int]
      name: ENC[AES256_GCM,data:ZfuhuA4=,iv:u5ejAP5ojqphWIba4bIDf8UXGbzQTPILH6O6ohVfR08=,tag:0PKCwizqqiDQunea/uEjfA==,type:str]
      vlanid: ENC[AES256_GCM,data:n9k=,iv:LJIjUv0ZXIz2emIUgDG7QQhAr3gRFCLOAPUyHpoE60g=,tag:r6Wv5cRxLS3ux21V4LS/0A==,type:int]
      node: ENC[AES256_GCM,data:2NcUVKQtl7mfcdHvh2QthNOh5vtUsKOK,iv:hvqeGJEF6RJaSQqj0PDv1AhNAjTFJ6K7aIXUVIwECJw=,tag:7Q/U5LAA17yPndvy3035yg==,type:str]
      mac: ENC[AES256_GCM,data:z8tysAZ2BW3Zk7SSHdZM4Hw=,iv:SpAJZ0+P2eLOsIY7XugVsMJNIikjg8yFv6r+EzW0ugA=,tag:8IPNl6icQpqPwLEtXWBMXg==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:M0LdSwDaYEyD4VLz,iv:VlRwYKCOlAqSGqI6NBrXEL+IOwGLW6ZJvCX5sXYImXw=,tag:EHMHi4gF8PnTPqdN/ag6LA==,type:str]
    - vmid: ENC[AES256_GCM,data:K+ix,iv:SuQDYi0tDhc/cU5+Q1d1Eo5lZnLmxsfEVePG+6/g4FA=,tag:fT0jIpeon/8uD2fgciQ34w==,type:int]
      name: ENC[AES256_GCM,data:0yErPfI=,iv:gdMiiciDozusnL5a7BXj5aWbNSQ+a9CG8Tb1TPup40c=,tag:c46zjvXq4c4JT91+m2Ozig==,type:str]
      vlanid: ENC[AES256_GCM,data:Z9w=,iv:GBmDkh4n1iCINbbKlm8n+rgTGiSElJ0RROZf4clYyZ4=,tag:Q1yNbNEcshnLrHDJVh0Vkg==,type:int]
      node: ENC[AES256_GCM,data:+zLkIRg9vtPWMYzNjtwFGZbBNzN/poCZ,iv:usJOvM5426tZUxMVtnjRsTbg541d4vo+AJUbQJX4BmQ=,tag:u+cFE2gsl5wg5LWb/NA1kQ==,type:str]
      mac: ENC[AES256_GCM,data:vwLeZSlWvJjUYloi1mCAfUk=,iv:+1k/ZGHh7/dW1f420H7pcQvvn+U5TdLy3+cIhBcDcm8=,tag:7FezN131FTUeOMbOkiXOWw==,type:str]
      memory: 16384
      storage: ENC[AES256_GCM,data:wWCMWHZrWY/CbqG01w==,iv:TvWw5qfCC0iPKjwxGxpVEuqI2SKLhdPOeFD+RpMoqUU=,tag:80zE5IxcgnX9FBwTXmUDUg==,type:str]
    - vmid: ENC[AES256_GCM,data:Hjcd,iv:LZhhRRuo9yW5mysaurCkZ6UOrwZt/ng4+dqZ07KW5Mk=,tag:/Thl8mnVUshwmLBI6BejuA==,type:int]
      name: ENC[AES256_GCM,data:pn7RQak=,iv:fEFqj7tTttxK/ftU3SbmsW00GCNjHB5hbJHRUK/mr6o=,tag:NUdx5oCXSn5/AK2aViivjA==,type:str]
      vlanid: ENC[AES256_GCM,data:YVo=,iv:/KxHjH92tWH+h7L7IC+azk0OrW/mrifvgqgFUkd/sf0=,tag:9xmbG1b4H/lgw8RB8GT95Q==,type:int]
      node: ENC[AES256_GCM,data:8E9WxfAzWBTMp03S14pAY5DroZkCqTWE,iv:edorNazxaCbTplD8FZ+7imqdHE+n6cNEL5MnkfIvcjk=,tag:fa9g8vH8L3XNefR+ssK73Q==,type:str]
      mac: ENC[AES256_GCM,data:1q9Z38WqlYREf+chRIFrUz0=,iv:t5zj+W/hgD6/OFonMzWYgkOx2BHK0aacgSp+hizTKpA=,tag:TBeMeXjo4WK/mVTKUW5ymg==,type:str]
      memory: 16384
      storage: ENC[AES256_GCM,data:rqN4/g5xu3FV9gparw==,iv:7j1124TVkLT+VRKplydInxoxzXulrS4Ul4ubKM6UTwI=,tag:4MKGW+lcUa5k1Kt7enQWXQ==,type:str]
    - vmid: ENC[AES256_GCM,data:NMyY,iv:gKmgld7GtaLhE+iI9ODf/g/3OlOK1lAF3D3GXQeXm7Q=,tag:YOCP4pDNI9mOdnODcy85cQ==,type:int]
      name: ENC[AES256_GCM,data:3grIRQo=,iv:/G1t+u9G535YNnPmoJXCiouh0wiEu+yqlzvoVDyfM3M=,tag:WbuFN5Fi6hI1YttYr09h4Q==,type:str]
      vlanid: ENC[AES256_GCM,data:ecQ=,iv:4BAeeU8+q1JPDx0pJXJ7QDglEkUaKbOC2k7SIx8ANRU=,tag:ljqNVIJboj0eSawYHNhwmg==,type:int]
      node: ENC[AES256_GCM,data:UN/q7Uqfo0OIJowqBeX53k6wrLjnzoZo,iv:WbMPNDkixWRRY4avGXBFfzIQtrJXd3VXyp3lJ+Y88Xc=,tag:WEucIk3CSiJCg40t3UulkQ==,type:str]
      mac: ENC[AES256_GCM,data:NbklrJaAW+Gtld2R9/aseCQ=,iv:j1RdE20WMYD24QsnpJ9hYjH/sW/mp4Wn4bGBES1H4eA=,tag:xEB+MUZHFEA1fitVCFbgJg==,type:str]
      memory: 16384
      storage: ENC[AES256_GCM,data:Rd7GYeNz7qP9DRpA8Q==,iv:VnHVvlQ3e4BGd2DPsICFRNbtmoduWr8YrLqk3VOWtZI=,tag:Fh881tvb5tnD4RjzeKEoxQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b3Z2Ry91ZE5rU1V5MTdh
        TmNJQWpuQXN5anFqV0pTN2xWNG90V3JMU1RzCldTUXJ4dmQxMlA1NzJhb3B4Vnhs
        UHlkc284alRuQ05GWjN3TEY4V0ZxYlUKLS0tIEhBTUNENU8zSjNvbTNLL2N6b05u
        UXdmNGhIeEF0ZjNXcVhONDNHRjM4QkkKzY1JdA2dNc9KNmy6au9itX7jx8/ER2Uj
        HiVnHsSL/eV3EPJuI8LdrOfn9aIphRbvT+rUDp+65B7Fv9j5H7SAnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-08T10:21:22Z"
  mac: ENC[AES256_GCM,data:NWD7Fgetdm7sLz3NShp7l2tP/tiFBLKCYxWepP7yr+BH9VuqD9S8atjm9GLaVfnG3zcB1bUIs7Gwgwsqea/vyZAP5Nvc/CoD1erxXiCjOzd0mqvB/EnlqeiJ/9XMKZmsQiwtlb8GLKt+HgPzpztGWUjFLuVLHESM3Kte2lbxt/M=,iv:gdH0iTkwY0Jw+UsvRtCDDfDHkKMo/j4Rvn3Uy7x76eg=,tag:6Jb+l4LKvzCnFbif24le7Q==,type:str]
  pgp: []
  encrypted_regex: ^(schematic-id|vip|controlplane-nodes|worker-nodes|node|vlanid|vmid|name|mac|storage|net0|password)$
  mac_only_encrypted: true
  version: 3.9.0
