# kubernetes/production/provision/proxmox-vm-config.yaml
apiVersion: v1
kind: Config
talos:
  schematic-id: 88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
  vip: 172.16.32.100
  controlplane-nodes: 172.16.32.101 172.16.32.102 172.16.32.103
  worker-nodes: 172.16.32.104 172.16.32.105 172.16.32.106
  node: 172.16.32.101
proxmox:
  common_vm_config:
    cores: 4
    cpu: x86-64-v2-AES
    bios: seabios
    boot: order=scsi0;ide2
    agent: enabled=1,fstrim_cloned_disks=1
    scsihw: virtio-scsi-pci
    scsi0: local-lvm:32
    cdrom: local:iso/talos-*talos_version-amd64.iso
    bootdisk: scsi0
  vms:
    - vmid: 400
      name: k8s-0
      vlanid: 32
      node: pve1.home.frandberg.live
      mac: BC:24:11:89:A2:8D
      memory: 8192
      storage: local-lvm:32
    - vmid: 401
      name: k8s-1
      vlanid: 32
      node: pve2.home.frandberg.live
      mac: BC:24:11:5A:92:8B
      memory: 8192
      storage: local-lvm:32
    - vmid: 402
      name: k8s-2
      vlanid: 32
      node: pve3.home.frandberg.live
      mac: BC:24:11:F2:AE:F4
      memory: 8192
      storage: local-lvm:32
    - vmid: 403
      name: k8s-3
      vlanid: 32
      node: pve1.home.frandberg.live
      mac: BC:24:11:F1:F2:5F
      memory: 8192
      storage: local-lvm:500
    - vmid: 404
      name: k8s-4
      vlanid: 32
      node: pve2.home.frandberg.live
      mac: BC:24:11:BE:37:B5
      memory: 8192
      storage: local-lvm:500
    - vmid: 405
      name: k8s-5
      vlanid: 32
      node: pve3.home.frandberg.live
      mac: BC:24:11:27:5E:89
      memory: 8192
      storage: local-lvm:500
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhK3hhWHVMSHFCamdaZjg0
        RUJjMlVIamxIeUJLSXBrNlVSNW5OQWIxbGs4CjFrL1pJa3BoSlZmQmxrM3grZUlN
        VVczTnZ5eUFlWkkxZGJMRTcwdy9hQ0EKLS0tIGIxWWxrVXVHY1orNFpFMDlpd0w5
        Yy9YdFpjOUJ3NTdQOUNBanJWSXVjbUkKRmPitFru8XT9J9JGEpEoUggPjCdAnOVV
        LcWQX6sW1+KX435YvMyr1Lc7UssBGWAR3rQvMCrVnT65Jcgx3PAQCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-17T09:25:52Z"
  mac: ENC[AES256_GCM,data:rWD3GWMz9iz1bJCJs+qt9UTtnbcZb7tPeqMN9LLQP6JqebFQq/DuFMsmUyTQQO6zS0jpbjQ72Iauv0IWsN3vUX+3VGwlrVzXgjkyEBNrcH96sB850nmj7k+Ce3R+jyzZBVDgYkd4Ax7/stSgRmRlWhml4fTtfhFuEMQsaJRzrMc=,iv:3L0n2URMLM/QG4FLuoK01EW9TwdMynBrz8lKDmLTN+g=,tag:qn6TVoRj5G+wR3WB6Z0BrA==,type:str]
  pgp: []
  encrypted_regex: ^(data||stringData)$
  mac_only_encrypted: true
  version: 3.9.0
