# kubernetes/production/provision/proxmox-vm-config.yaml
apiVersion: v1
kind: Config
talos:
  schematic-id: ENC[AES256_GCM,data:hwtnoTIUCYAfF9W8fDhIO9iY/yrynaiZZCa+CD4RWNIILrMVkBKOff+OeCZzu1AYnUSo6zuQMe6klkhXBeSnKw==,iv:tvgGsWtdyEMXhhRJnSkf9RAUb2c9ENN0JDwo8UOmG1c=,tag:7DKAc4KYM0QyKwpfRrqqxw==,type:str]
  vip: ENC[AES256_GCM,data:T9dUPa6aI/7gECD2ug==,iv:4BxOqxAas+7b5rv7iAIFBlzyR02Cq2iO9t+oeCLpOTQ=,tag:1WfVFIMIYlkJ4t0rV723tw==,type:str]
  controlplane-nodes: ENC[AES256_GCM,data:tgoZLV4Ovq2d/gLbFI45D0TBfBx5v8e6AQwLtvn/ygg4iglbrX1Qn58=,iv:NVBCVam+S0IIMZbEAsWWIVrCkQNsUqKpskHWGjvK9QI=,tag:K8NJCaP1WqN9MyNbiCwvUQ==,type:str]
  worker-nodes: ENC[AES256_GCM,data:9FvBROShgSIYMj715p0hnl5hC6KA3uRE5ur8J6negD5ySwEG6ZT69Aw=,iv:r5eDrNt9Cm0HCWDkc4yjyFlDup0UaFE7zDittXxjiUs=,tag:r8OeJe0jl2jFxODw7hTDJQ==,type:str]
  node: ENC[AES256_GCM,data:UYbqyT2s2VNSJVtyHQ==,iv:xhqkdmvtL7Y1R6q1TDMR2O34yMfXky7jwgYWBun7Dvo=,tag:PBoF3XFwnNkBGSkSni823A==,type:str]
proxmox:
  talos:
    version: v1.7.6
  common_vm_config:
    cores: 4
    cpu: x86-64-v2-AES
    bios: seabios
    boot: order=scsi0;ide2
    agent: enabled=1,fstrim_cloned_disks=1
    scsihw: virtio-scsi-pci
    scsi0: local-lvm:32
    cdrom: local:iso/talos-*talos_version-amd64.iso
    bootdisk: scsi0
  vms:
    - vmid: ENC[AES256_GCM,data:ZxdV,iv:Nk+uZj4+tLZ4Y1e6LyzyTXGsKHjHi+sgbZu643OEOY4=,tag:imYPrh8AZBfdYGCpPqnECw==,type:int]
      name: ENC[AES256_GCM,data:00n4SVo=,iv:FXrjbGQq+5LqhjYPZ1DgOKg/4FiuiazU16Xp8XgB1+Q=,tag:pC3f/cPJfOBXOLzrmnVStg==,type:str]
      vlanid: ENC[AES256_GCM,data:hKU=,iv:dGq+FbFnex82s79tvNtw4KKVF862grPAAPuu8QKMgjs=,tag:+zIEi/qdW6nU5fICjaa5eA==,type:int]
      node: ENC[AES256_GCM,data:qUVsbAI3VrP7obD/Mp8Y3jYTjkuocWqg,iv:jpOjEGgQEoqXRrq1oiI2CcgHC24JQe4cs0Oneboi3O8=,tag:vvd8GKUkot2zFbqIpTJPzw==,type:str]
      mac: ENC[AES256_GCM,data:pP/ka9GQs8FqV0tOBVJjCas=,iv:M3L2zl1GydtoE4FEdRupjalxcw1azCYXs2tYcUkrXfQ=,tag:2hLKIl9SO6TYeutQROoB8A==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:FZG6GAqETMZ0aVEP,iv:Moh58ASUYejIeuepJyT1KPyefec2X5f5tuwQdXSQIHM=,tag:MZe04eMx4p2MNuDW9orWwQ==,type:str]
    - vmid: ENC[AES256_GCM,data:j1Y+,iv:1edX3OwNngakQbs8Ro/IRAVA6ZbqSFwwYQZgTMHomwc=,tag:nZWG1J1aFQ46vr6uoX0kZA==,type:int]
      name: ENC[AES256_GCM,data:AUdBmoE=,iv:PBWarQyBHyoSonia6RIBNtoM4jFbm33q4VCygcgbmgg=,tag:Iiy2Hn6PEbmYaCszCoLadA==,type:str]
      vlanid: ENC[AES256_GCM,data:Rz8=,iv:nVe6yiZQ+X5xQoKCXljtsdNViDYDvBsxok0wxUzbJig=,tag:QTSYB8Rjae+RXPzp/auI/Q==,type:int]
      node: ENC[AES256_GCM,data:G0ydHoM/K/mTpiVxCFgZZSh7XxM7uYxs,iv:Bbh0cDnbOSRjhZ2yoEWcfzO63JTFFdxZIoFZl8oNGV8=,tag:FGBmWr2zw9xB3tJ5zbwQIQ==,type:str]
      mac: ENC[AES256_GCM,data:m4jXWAo4UylrQmoHTm4QSbM=,iv:HhlcYtgcJCHmSMZHCmCgrEv3wGwcXKvp4sUYW871FP4=,tag:8MQr8fjnNE4thbNLS0Qlxw==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:yocBdyH1zWNPWwkd,iv:DkoBzkol/hQJoa5vIQ//uYEtwilsB9gmdZZobxJCs0A=,tag:xPG+BHkwG/WJpx/Legh12A==,type:str]
    - vmid: ENC[AES256_GCM,data:ZntS,iv:+XaYi+UTRMyz0Kgqyh/KpSpwq7+SV95sOKcYqAtS6kA=,tag:YZ822GN2J0ORa2/FX7XIIA==,type:int]
      name: ENC[AES256_GCM,data:N51AFGY=,iv:nS3Muz945mgQMCg3KztF89xqAnOzR1ekhRFN21MlJ2s=,tag:5rUUrlr9wB43Sqd+u7ENAA==,type:str]
      vlanid: ENC[AES256_GCM,data:OMw=,iv:2hhT2NS4TsYBs9wataBGY8oxr0hxgGCfwXokDKbRZPw=,tag:U/FJInU2wfLR76i9WykcKA==,type:int]
      node: ENC[AES256_GCM,data:M2Oq5+3/7ZrKfOdbuPakJvkYUXJvtghG,iv:f+2YANg2fPyIaipbNj4mGW7567G5LaUPpnFBc0IRsU4=,tag:cA3pQvNF27PlEadLMxcD8A==,type:str]
      mac: ENC[AES256_GCM,data:B2ludr0pe5ZZ5jVNO91dUmc=,iv:eiC6b1Vs0A1dQDU0FM51BirFEKx/3CL8dFiH+v0bQwM=,tag:B7mzShO9gDmWJQGejhnCCg==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:nnw+eH7F28e5I/TF,iv:lAyHwj2buAnPAoLadF6pwsLhUsELRbEExOkVbac+5Q0=,tag:vcng8K4IhTjvRkQ+HxEMdQ==,type:str]
    - vmid: ENC[AES256_GCM,data:A9t9,iv:QQYAurgEkOd3r/7hTFp8Ro6lBdMOzeBLf6PAIKLxc9o=,tag:3Gd49o6++gfRMsY9Y62gLw==,type:int]
      name: ENC[AES256_GCM,data:6zMnFr4=,iv:a9AAj0ZICqOGDuOAsUfba/LEl7ZuwZ8i/sLPeYKXm2I=,tag:gMvG8vlsjlWc6d0Mi2Er4A==,type:str]
      vlanid: ENC[AES256_GCM,data:PMc=,iv:67KobiBCut1RBe9Cpb0hGNgUtVDyi2S6DsCsC7H4+Wc=,tag:QOYM66Uw3+8ihtGtzya6NQ==,type:int]
      node: ENC[AES256_GCM,data:namaOKMGH9iUqoGAdAccsATaQuZUjwQy,iv:QOa1Qn7sdOaXkaivyNBwC6YaEGo0pAc/6SfoVmvJFpw=,tag:Gg2MElGWNYrVHyAKRw5Amw==,type:str]
      mac: ENC[AES256_GCM,data:6lBTYcWMkGfj9AytstDEGf4=,iv:YP7mgRu5at7xPDnoVVaZ+lpt1xIc9m8R6GhBIkDl4Ig=,tag:bz97xD9l3YvOLZdL31cBeg==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:l6u6hsKkKjEDv20Qjw==,iv:fk3EHb1QyM6VRDIACgBm1JI74K9FTXHQ/4dLhYrji1k=,tag:oML041pnSpNsS8+TpqwRHQ==,type:str]
    - vmid: ENC[AES256_GCM,data:gBPT,iv:Xl0aBikcBN88uCquOM/Dd373lX23p0rbKpRRVBgRWLA=,tag:nAnLPjCkLs+tjOjdg/6/AQ==,type:int]
      name: ENC[AES256_GCM,data:M2Hw/xM=,iv:jfOWiKi1Pvs7XuVM+U+d4KhPRet5//Qoy2osAI4wPMI=,tag:oCt+oYUF2OHaGW48GNtDjA==,type:str]
      vlanid: ENC[AES256_GCM,data:9uw=,iv:AYfd5C29ahRMKdDVvFlfO61uVJs8+j/AQGES1+A/8Mo=,tag:XyAbzwL+yfdi+BiiL5CPOQ==,type:int]
      node: ENC[AES256_GCM,data:oYeK6COieN33WjDhFWpkdl9lDerPc/K9,iv:ZCZW72A4IMRmDPRn7I5uGLKYbkoS2VuLpRvyUeHp1f8=,tag:WEUkfHnwQputdtmCd6e4QQ==,type:str]
      mac: ENC[AES256_GCM,data:rWK3CcrfJbXes2LdR71i8b0=,iv:Kq9ZEDSeP2avZFcDvRHKXc4hbVXYmT2uSgoV9USxeeQ=,tag:cSGvpSIMqsjDSPcvDPZ9GQ==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:tJ5L0LfXWu1QCYqvBA==,iv:RylihNaxlDbBs0omPLFRJkP+MiPgXrDIYpmKCF7UWag=,tag:yNEWE1xhqLE5RGmj9W27jQ==,type:str]
    - vmid: ENC[AES256_GCM,data:RMzs,iv:8FJ/gqDKxjOzuy4eruX+1vldYLoYQ9xNFjMe8RytKkQ=,tag:jOyhIULTO7eK2y9OIzD6EA==,type:int]
      name: ENC[AES256_GCM,data:4ExwY2I=,iv:4rstJENhHkZaxKryt1/flKiBOqcBYO685NKPrN6VX2k=,tag:4zPb4+2wy3MBRfpaEzsAxg==,type:str]
      vlanid: ENC[AES256_GCM,data:6PI=,iv:HU5ff5u7A/oe9zOAnSEzNenxSPZ30FZlUqS2cJw5mSs=,tag:U/WGr55c5LONWhIfaM1TiQ==,type:int]
      node: ENC[AES256_GCM,data:12m6qAlsE98/5HTIyOOiIikslF9qkKGA,iv:2vwTVzV6HLT2IbVYnr5K6sCAexGr0qE2D/ZoElTua0Q=,tag:8XR6Nd/q2VQzSQLWCa55iA==,type:str]
      mac: ENC[AES256_GCM,data:f0aLNzGaqgpyNaSQ2pS4hXE=,iv:DHdZu3B31RxgLyezCUA6aV1foK2X0lmszu0sdqgAo5E=,tag:BMDIUWopt4Ie75Kng1DTbw==,type:str]
      memory: 8192
      storage: ENC[AES256_GCM,data:mJZ+WjSdwbBA4LM/lw==,iv:mwI50MnYAWqIAk4cG7ihCJdGKpdf6muUgPOmW/iHt/0=,tag:B7aR5MGPFYWp1ZA9HWGcTg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNmhMNUxYaUZaYnBoNW9u
        Y1BlR3ZvOUg1WDE3RlZ5S2pRbCsxK1NzWkVjCnFsbTJjeWwwVlVHVEJCc0pnOHla
        cmplVjRRSmlMcmRlYnZhazJlUFV0aHMKLS0tIEQxOUJxeUhFREhMYVVnWFNJRWJs
        ZXNuMXRVTEpsRnk0K3FnY05OcU9rbU0KghL/GtIcw78ZPAZ9ywncg8Z3vt+DR3aS
        4B6264xeKXN6Eg5CQniucBasJnGGFkWzGhS6ejX8SicR2MyvwIPB0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-05T17:03:17Z"
  mac: ENC[AES256_GCM,data:9X5l74Z3P8O1UeT5quoNxwVvPVRwBNlgzpAF+k3cLT64Hp5h4n5Jgw/1zeqUGwik1akA67p01U0oJn/iAd0ZJBLmUYnWFYLtL7dtorjfKdPR5gcOichB+VOwwOpPIB7xV43U2rl/Bb34A8RO9BuQsxBNa2pcxHcHicq9mJJK6FA=,iv:zqpuXKrczp4czWTWigVg4mhrTagNEFC4Qn5MJMWImO8=,tag:QXAhI3u+FzFK2vNgyuesPQ==,type:str]
  pgp: []
  encrypted_regex: ^(schematic-id|vip|controlplane-nodes|worker-nodes|node|vlanid|vmid|name|mac|storage|net0|password)$
  mac_only_encrypted: true
  version: 3.9.0
