---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  driftDetection:
    mode: enabled
  values:
    alloy:
      configMap:
        create: false
        name: alloy-config
        key: config.alloy
      clustering:
        enabled: true
        name: alloy
      storagePath: /var/lib/alloy
      enableReporting: false
      mounts:
        extra:
          - name: alloy
            mountPath: /var/lib/alloy
      extraVolumes:
        - name: snmp-modules-volume
          configMap:
            name: snmp-modules-config
      extraVolumeMounts:
        - name: snmp-modules-volume
          mountPath: /etc/snmp/snmp_modules.yaml
          subPath: snmp_modules.yaml
      stabilityLevel: experimental
      extraPorts:
        - name: syslogx
          port: 514
          targetPort: 514
          protocol: UDP
    controller:
      type: "statefulset"
      replicas: 1
      enableStatefulSetAutoDeletePVC: true
      volumeClaimTemplates:
        - metadata:
            name: alloy
          spec:
            accessModes: [ReadWriteOnce]
            storageClassName: longhorn
            resources:
              requests:
                storage: 5Gi
