---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alloy
  annotations:
    kubernetes.io/ingress.class: traefik-external
    external-dns.alpha.kubernetes.io/target: traefik.${SECRET_CLUSTER_LOCAL_DOMAIN}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`alloy.${SECRET_CLUSTER_LOCAL_DOMAIN}`)
      kind: Rule
      services:
        - name: alloy
          port: 12345
  tls:
    secretName: observability-certificate-secret-production

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: alloy-ingress-udp
  labels:
    app.kubernetes.io/name: syslog
  annotations:
    kubernetes.io/ingress.class: traefik-external
    external-dns.alpha.kubernetes.io/target: traefik.${SECRET_CLUSTER_LOCAL_DOMAIN}
spec:
  entryPoints:
    - syslog
  routes:
    - services:
        - name: alloy
          port: 514
# tls:
#   secretName: observability-certificate-secret-production
