---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik-charts
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://traefik.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      version: 33.0.0
  interval: 10m0s
  values:
    deployment:
      replicas: 1
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
    additionalArguments:
      - "--log.level=DEBUG"
      - "--providers.kubernetesingress.allowemptyservices=true"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowemptyservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
    ports:
      traefik:
        expose:
          default: true
      web:
        redirectTo:
          port: websecure
      websecure:
        tls:
          enabled: true
      mqtt:
        port: 1883
        protocol: TCP
        redirectTo:
          port: mqttsecure
      mqttsecure:
        port: 8883
        protocol: TCP
        expose:
          default: true
        exposedPort: 8883
        tls:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: false
    rbac:
      enabled: true
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: traefik.${SECRET_CLUSTER_LOCAL_DOMAIN}
        external-dns.alpha.kubernetes.io/owner-id: main
        lbipam.cilium.io/ips: 172.16.32.99
      enabled: true
      type: LoadBalancer
      labels: {}
