apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GYVg2ZBuiHCbQVN9cj8fy2bVvgni61cmRCVzhQ==,iv:urkTmzLgS3yO4VzttTj2/LN9M90j/V7FDgO9HUvs/YA=,tag:LtKhhQGkEetue/Cm/e9iqA==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:wJGtCr8VHZ77O4y8s4nQxWwweHJl4c7/KMcXcEhtnmpB27XxZGBGkpxps1fVQ/Ac,iv:npJQIJv0ppsohTgH/f/DNhYxvn1QVh09bQT86FsDKp8=,tag:Ic/i0qS15MeQXAEZt2CTpg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:t/QZF62Ubf2eDRkz4AyR5khvjcQqSEXcJMz97x+yBNKunD/JKJ1QNrn1giA9mR/9BwAUVIePphM=,iv:JC1t4PieKDn7TUBwWPi04PJW1l9KS68rvgPfBERqsvk=,tag:6rfnlU09hBJils0OF5WiBQ==,type:str]
kind: Secret
metadata:
  name: longhorn-truenas-s3-backup-credentials
  namespace: longhorn-system
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMkh2M1NjVWJ3blJsMlJu
        NHdqSWxUdkR2K29TZk5Nc2NLNjBuaTBmaFRvCm40V2U5WFVQdjlhbVNNK0syNGkr
        Vkh6TlVGbXA3aDNFU1dhY25nSUJMMlUKLS0tIHRKSkI4WTFBN0pyekVIazBUR1pD
        VWZyam1UcGNYdFcwQXYxaVZtaURraEEKnOBXRVn1BqfQfwgvp43Qcl+X94HX8/rI
        FCHZwbNY4IRQE2sHkGFrEhcCoLet5WFKIq0JAB4uUeyVm9XGShVNHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-03T14:35:21Z"
  mac: ENC[AES256_GCM,data:Zx79ZP2qOypUQQMRRx35+Lz7zxW5Et8PxZB2Le0JrOi2Cz+wPXWb6WWaGFIawcemCai65OdqEkfmzx7EjHFxI3hjDO6yyI1RKVGlV+aYZHDBR87Kkhy6zIuIXGNXtBTTdVP4ELbjnHSTSka/gSBqckDrmpBDa4AjDK6aLz1vlK8=,iv:zUkY7wNOmno0XYqFxLFPUEJSC5Cm4PrDFyRPYxIZOP8=,tag:x1IEG2p1pQAOeFH5CD5rzg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|ip)$
  mac_only_encrypted: true
  version: 3.9.0
