apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:epRPDg+k4Lx8mKjArs3sKZf7WJPrXVDpGxShoH48fCRod706s9KM0g==,iv:LH70Sn15S1fnwfc0QeUViJYDOCvVmh/3IcWWanZ0GFE=,tag:tN0x0sxixZBnmEPiDnOOiw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRVdyelQzSkh0clVXU2Jy
        SHovUFlpWms0ZlU4ckFOcHMyTlJsS1E3d25NCkFXcXZFOGZMdHovdjdESlpQU1gw
        T1dKSVdRVnJMM0sxZUVaRVRNY01mTmMKLS0tIE5OelhPN1VtcElldEYyNGE1OUht
        dUIwZTlycEdWS1hhSXEzRjJBWm1tUlUKZudS7jfkoJ7HVMAcDps/gROyv8WhUHlW
        L8F+C15Z/kvR8fYaNzmdPRO3zx9AWq7PK861YmVfr2HQQ+UhLnQs/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-19T18:15:32Z"
  mac: ENC[AES256_GCM,data:8AXq9jS1CwmeTJm2CPsZus40JRTyQVW25K/51RXVacKr3KeFu7Fc/xsY5lLGHxoFKromg1qtPCLOrQHr9R7lt6+HgRsGg/p5kVumb+3nrH1ouoQgH02f7Aug+3auuOwI7HoyVE1KxFcdzXIL13POZLHfcMZjUZhTjKrzv+tm6CA=,iv:V3Fryk3Y4xdCGrwMbAk2JLi47bSI3eNl4MH6NozGS98=,tag:iGYD3JXBaAV8YgNkKXlEag==,type:str]
  pgp: []
  encrypted_regex: ^(data||stringData)$
  mac_only_encrypted: true
  version: 3.9.0
