apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:Gtx8beMZxAuB43da7PmUkSpJJ0pepRYcD4E687owZ8XQJt6w3ayVsw==,iv:Juc1qEegfWQcapHmaU9/4mVr0bQj+/MKCEi+EvkznA0=,tag:wDCfvrVmNat9vEEk1hJyBg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT3JmVU1pdVkvc1ZObEVQ
        L0NBc2t5TCs0QTVyNmtJLzZDUzNYSjlnZVY0Ck9lbWNmSXY0Q0lYS0psUXRVc1BU
        MDYzQ2ZxS3F5d2ZmbGtoMzEyT0pPdXcKLS0tIEQ2RHlrK3UyZzA4QW10eGhqY3o3
        YkYrSTFrRXFxQTl2Z3RuVFlNcnVJL2cKZcjO4fqj9ErbC24m2sPXsQn739wV3TnE
        8Du7rSTxWjZKm2v8rffMKQ7iff+edfZWiLu5OCkpe62KizL9LEXnTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-19T17:56:47Z"
  mac: ENC[AES256_GCM,data:dESr5gASbXf/lce0LKNGoUKzFLQKD7RcsZTxApqXNHU9H2xhi/h0RKQblWcdf2nFHFU7n+4SsmAbMoog3P0M3T8INgF32ZVPlGtdtbKIVT525cRWdoS1pxwm0qSjO5qi6ix8cZBOz5iboiyHvCC2kUv1egpYZ2QJifX23kJJGRo=,iv:0jYbdVoqydi6anNGXNFCEzzzvU0HWvlLl8aeTKgzeO0=,tag:q3BxCxHihA8XYJ1RhnyO8g==,type:str]
  pgp: []
  encrypted_regex: ^(data||stringData)$
  mac_only_encrypted: true
  version: 3.9.0
