apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: ENC[AES256_GCM,data:PZiqpPwmMY+jqQ/QEMyWY4FXQ4zeCrjlnYx4khn/mmTqEMLlag9y3g==,iv:QfTdNoRmffwM1bVF+6HsgHhEY5qXO8r+LXTCMfBiSBg=,tag:JWg6wDl7KJW5k29W1ul7AA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYXpFTWJ0aUVMNVZPVlBO
        Um9MN2ovcWJXL1ZOUDVRMzNkNzFYZEk0bVhvCm4yZ21Mb0dZVy9FakFtck5NNkV5
        eXBjYi8vTVFMRDFLR2tQR1p5dGJPbFUKLS0tIGxVdUlMMUhDUUlmWmtXc2JUcnNY
        a1MxRnV1ajBOR1I2NFdyNlZEZ1QzdWMK8fiGxfGu0msqwvHE1FT4dzuUC5EIcEw9
        FFEJLnn2TE7gdyupyiQvttyz9QixF2YWMCm0+st/G9rofhMcaThjiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-06T18:40:02Z"
  mac: ENC[AES256_GCM,data:OQqEIjR28VKZYeSimdPD6Ig+drHzokS+bNMdcLEPF2RRJ8+1Ybgpg5C9WG7xZDM5z3kCFJOPJWpdtEdEscYNH/OkoT0ASEfL2R8c1PrwO8n0U3Vc5EuzTKqHVC6qd6GYtKtXhYzbRdOU4z6/ijpcwnI/vw/wANVfdS4+DZprHVs=,iv:96Wv0RBlDxsjbr7WgqEk+ayUaaR8BUgQdh/5GSRoI5k=,tag:HGUQtdhrQeFazyqzscIo6Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|ip)$
  mac_only_encrypted: true
  version: 3.9.0
