# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: cloudflare-clusterissuer-staging
# spec:
#   acme:
#     # Replace the email address with your own contact email
#     email: "${SECRET_CLOUDFLARE_EMAIL}"
#     # The server is replaced in /clusters/production/infrastructure.yaml
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: cloudflare-clusterissuer-staging-account-key
#     solvers:
#       - dns01:
#           cloudflare:
#             email: "${SECRET_CLOUDFLARE_EMAIL}"
#             apiTokenSecretRef:
#               name: cloudflare-api-token-secret
#               key: api-token
#         selector:
#           dnsZones:
#             - ${SECRET_DOMAIN}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer-production
spec:
  acme:
    # Replace the email address with your own contact email
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-clusterissuer-production-account-key
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_CLOUDFLARE_EMAIL}"
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
