apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.20
          ports:
            - containerPort: 1883  # MQTT port
          env:
            - name: MOSQUITTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mosquitto-password
                  key: mosquitto_password
          args: ["-c", "/mosquitto/config/mosquitto.conf"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config
            - name: data
              mountPath: /mosquitto/data
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
