---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mosquitto-ingress-tcp
  labels:
    app.kubernetes.io/name: mosquitto
  annotations:
    kubernetes.io/ingress.class: traefik-external
    external-dns.alpha.kubernetes.io/target: traefik.${SECRET_CLUSTER_LOCAL_DOMAIN}
spec:
  entryPoints:
    - mqttsecure
  routes:
    - match: HostSNI(`mqtt.${SECRET_CLUSTER_LOCAL_DOMAIN}`)
      services:
        - name: mosquitto-service
          port: 1883
  tls:
    secretName: production-tls
    certResolver: letsencrypt-production
    passthrough: false
