# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
spec:
  interval: 30m
  chart:
    spec:
      chart: mimir-distributed
      version: 5.7.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    usage_stats:
      enabled: false
    query_scheduler:
      replicas: 1
    querier:
      replicas: 1
    alertmanager:
      persistentVolume:
        storageClass: longhorn
    ingester:
      replicas: 2
      zoneAwareReplication:
        enabled: false
      persistentVolume:
        storageClass: longhorn
        size: 70Gi
      resources:
        limits:
          memory: 12Gi
    store_gateway:
      zoneAwareReplication:
        enabled: false
      persistentVolume:
        storageClass: longhorn
    compactor:
      persistentVolume:
        storageClass: longhorn
        size: 20Gi
    minio:
      enabled: false  # Mimir helm chart deploys minio by default, if you prefer to use your own mimio instance, disable it as i did
    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              access_key_id: ${MINIO_MIMIR_ACCESS_KEY}  # Create Secret and Access key inside you minio instance and type access_key_id here
              bucket_name: mimir-ruler  # Create this bucket inside your minio instance
              endpoint: ${MINIO_MIMIR_URL}  # Enter the url of your minio instance, NOTE: Do not include http or https
              insecure: false  # if your instance does NOT support <<https>>, change it to true
              secret_access_key: ${MINIO_MIMIR_SECRET_KEY}  # Create Secret and Access key inside you minio instance and type secret_access_key here
        blocks_storage:
          s3:
            bucket_name: mimir-tsdb  # Create this bucket inside your minio instance

        alertmanager_storage:
          s3:
            bucket_name: mimir-ruler  # Create this bucket inside your minio instance

        ruler_storage:
          s3:
            bucket_name: mimir-ruler  # Create this bucket inside your minio instance
