---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Yamllint

on:
  push:
    branches: ["main"]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint
        run: yamllint .
